# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_app_t.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1283, 1024)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_lbl_grn = QtWidgets.QLabel(self.centralwidget)
        self.lbl_lbl_grn.setEnabled(True)
        self.lbl_lbl_grn.setGeometry(QtCore.QRect(600, 48, 96, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_lbl_grn.setFont(font)
        self.lbl_lbl_grn.setObjectName("lbl_lbl_grn")
        self.lbl_lbl_product = QtWidgets.QLabel(self.centralwidget)
        self.lbl_lbl_product.setGeometry(QtCore.QRect(198, 48, 116, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_lbl_product.setFont(font)
        self.lbl_lbl_product.setObjectName("lbl_lbl_product")
        self.lbl_product = QtWidgets.QLabel(self.centralwidget)
        self.lbl_product.setGeometry(QtCore.QRect(308, 48, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_product.setFont(font)
        self.lbl_product.setObjectName("lbl_product")
        self.lbl_grn = QtWidgets.QLabel(self.centralwidget)
        self.lbl_grn.setEnabled(True)
        self.lbl_grn.setGeometry(QtCore.QRect(700, 48, 171, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_grn.setFont(font)
        self.lbl_grn.setObjectName("lbl_grn")
        self.lbl_date_time = QtWidgets.QLabel(self.centralwidget)
        self.lbl_date_time.setEnabled(True)
        self.lbl_date_time.setGeometry(QtCore.QRect(944, 36, 327, 61))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_date_time.setFont(font)
        self.lbl_date_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_date_time.setObjectName("lbl_date_time")
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setEnabled(True)
        self.btn_back.setGeometry(QtCore.QRect(14, 36, 123, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet(" QPushButton {\n"
"    border-style: ridge;\n"
"     border: 2px solid DarkSlateGray;\n"
"     border-radius: 6px;\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
" }\n"
"\n"
" QPushButton:pressed {\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
" }\n"
"\n"
" QPushButton:!enabled {\n"
"     background-color:DarkGray;\n"
" }\n"
"")
        self.btn_back.setObjectName("btn_back")
        self.twInfoBoard = QtWidgets.QTabWidget(self.centralwidget)
        self.twInfoBoard.setGeometry(QtCore.QRect(28, 700, 1229, 283))
        self.twInfoBoard.setObjectName("twInfoBoard")
        self.tab_info = QtWidgets.QWidget()
        self.tab_info.setObjectName("tab_info")
        self.lbl_lbl_units_fail = QtWidgets.QLabel(self.tab_info)
        self.lbl_lbl_units_fail.setEnabled(True)
        self.lbl_lbl_units_fail.setGeometry(QtCore.QRect(941, 14, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_lbl_units_fail.setFont(font)
        self.lbl_lbl_units_fail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_lbl_units_fail.setObjectName("lbl_lbl_units_fail")
        self.lbl_lbl_units_tested = QtWidgets.QLabel(self.tab_info)
        self.lbl_lbl_units_tested.setEnabled(True)
        self.lbl_lbl_units_tested.setGeometry(QtCore.QRect(38, 14, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_lbl_units_tested.setFont(font)
        self.lbl_lbl_units_tested.setObjectName("lbl_lbl_units_tested")
        self.lbl_units_pass = QtWidgets.QLabel(self.tab_info)
        self.lbl_units_pass.setEnabled(True)
        self.lbl_units_pass.setGeometry(QtCore.QRect(692, 16, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_units_pass.setFont(font)
        self.lbl_units_pass.setObjectName("lbl_units_pass")
        self.lbl_lbl_units_pass = QtWidgets.QLabel(self.tab_info)
        self.lbl_lbl_units_pass.setEnabled(True)
        self.lbl_lbl_units_pass.setGeometry(QtCore.QRect(520, 14, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_lbl_units_pass.setFont(font)
        self.lbl_lbl_units_pass.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_lbl_units_pass.setObjectName("lbl_lbl_units_pass")
        self.lbl_units_fail = QtWidgets.QLabel(self.tab_info)
        self.lbl_units_fail.setEnabled(True)
        self.lbl_units_fail.setGeometry(QtCore.QRect(1112, 16, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_units_fail.setFont(font)
        self.lbl_units_fail.setObjectName("lbl_units_fail")
        self.lbl_units_tested = QtWidgets.QLabel(self.tab_info)
        self.lbl_units_tested.setEnabled(True)
        self.lbl_units_tested.setGeometry(QtCore.QRect(208, 18, 79, 25))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_units_tested.setFont(font)
        self.lbl_units_tested.setObjectName("lbl_units_tested")
        self.btn_lbl_start = QtWidgets.QPushButton(self.tab_info)
        self.btn_lbl_start.setGeometry(QtCore.QRect(266, 78, 787, 130))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.btn_lbl_start.setFont(font)
        self.btn_lbl_start.setStyleSheet("background-color: rgb(236, 236, 236)")
        self.btn_lbl_start.setObjectName("btn_lbl_start")
        self.twInfoBoard.addTab(self.tab_info, "")
        self.tab_debug = QtWidgets.QWidget()
        self.tab_debug.setObjectName("tab_debug")
        self.lcdLoop = QtWidgets.QLCDNumber(self.tab_debug)
        self.lcdLoop.setGeometry(QtCore.QRect(1118, 22, 90, 37))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lcdLoop.setFont(font)
        self.lcdLoop.setStyleSheet("/**** QLCDNumber (enabled) ****/\n"
"QLCDNumber\n"
"{\n"
"  border: 1px solid rgb(20,20,20);\n"
"  color:rgb(0, 0, 74)\n"
"}\n"
"\n"
"/**** QLCDNumber (disabled) ****/\n"
"QLCDNumber:disabled\n"
"{\n"
"  background-color: rgb(120,120,120);\n"
"  border: 1px solid rgb(60,60,60);\n"
"}")
        self.lcdLoop.setDigitCount(4)
        self.lcdLoop.setProperty("value", 0.0)
        self.lcdLoop.setObjectName("lcdLoop")
        self.pb_pf_t17_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t17_0.setGeometry(QtCore.QRect(669, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t17_0.setFont(font)
        self.pb_pf_t17_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t17_0.setObjectName("pb_pf_t17_0")
        self.pb_pf_t26_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t26_1.setGeometry(QtCore.QRect(1016, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t26_1.setFont(font)
        self.pb_pf_t26_1.setObjectName("pb_pf_t26_1")
        self.pb_pf_t5_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t5_3.setGeometry(QtCore.QRect(202, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t5_3.setFont(font)
        self.pb_pf_t5_3.setObjectName("pb_pf_t5_3")
        self.pb_pf_t28_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t28_1.setGeometry(QtCore.QRect(1089, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t28_1.setFont(font)
        self.pb_pf_t28_1.setObjectName("pb_pf_t28_1")
        self.pb_slot_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_slot_2.setGeometry(QtCore.QRect(1, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_slot_2.setFont(font)
        self.pb_slot_2.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_slot_2.setObjectName("pb_slot_2")
        self.pb_pf_t18_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t18_1.setGeometry(QtCore.QRect(708, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t18_1.setFont(font)
        self.pb_pf_t18_1.setObjectName("pb_pf_t18_1")
        self.pb_pf_t21_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t21_2.setGeometry(QtCore.QRect(826, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t21_2.setFont(font)
        self.pb_pf_t21_2.setObjectName("pb_pf_t21_2")
        self.pb_pf_t29_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t29_2.setGeometry(QtCore.QRect(1130, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t29_2.setFont(font)
        self.pb_pf_t29_2.setObjectName("pb_pf_t29_2")
        self.pb_pf_t14_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t14_4.setGeometry(QtCore.QRect(553, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t14_4.setFont(font)
        self.pb_pf_t14_4.setObjectName("pb_pf_t14_4")
        self.pb_pf_t23_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t23_0.setGeometry(QtCore.QRect(901, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t23_0.setFont(font)
        self.pb_pf_t23_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t23_0.setObjectName("pb_pf_t23_0")
        self.pb_pf_t6_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t6_2.setGeometry(QtCore.QRect(242, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t6_2.setFont(font)
        self.pb_pf_t6_2.setObjectName("pb_pf_t6_2")
        self.pb_pf_t18_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t18_4.setGeometry(QtCore.QRect(708, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t18_4.setFont(font)
        self.pb_pf_t18_4.setObjectName("pb_pf_t18_4")
        self.pb_pf_t14_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t14_1.setGeometry(QtCore.QRect(553, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t14_1.setFont(font)
        self.pb_pf_t14_1.setObjectName("pb_pf_t14_1")
        self.pb_pf_t25_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t25_4.setGeometry(QtCore.QRect(978, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t25_4.setFont(font)
        self.pb_pf_t25_4.setObjectName("pb_pf_t25_4")
        self.pb_pf_t10_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t10_4.setGeometry(QtCore.QRect(397, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t10_4.setFont(font)
        self.pb_pf_t10_4.setObjectName("pb_pf_t10_4")
        self.pb_pf_t18_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t18_0.setGeometry(QtCore.QRect(708, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t18_0.setFont(font)
        self.pb_pf_t18_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t18_0.setObjectName("pb_pf_t18_0")
        self.pb_pf_t24_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t24_0.setGeometry(QtCore.QRect(939, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t24_0.setFont(font)
        self.pb_pf_t24_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t24_0.setObjectName("pb_pf_t24_0")
        self.lbl_fail_t12 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t12.setEnabled(True)
        self.lbl_fail_t12.setGeometry(QtCore.QRect(471, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t12.setFont(font)
        self.lbl_fail_t12.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t12.setObjectName("lbl_fail_t12")
        self.pb_pf_t7_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t7_2.setGeometry(QtCore.QRect(281, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t7_2.setFont(font)
        self.pb_pf_t7_2.setObjectName("pb_pf_t7_2")
        self.pb_pf_t20_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t20_1.setGeometry(QtCore.QRect(786, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t20_1.setFont(font)
        self.pb_pf_t20_1.setObjectName("pb_pf_t20_1")
        self.pb_pf_t19_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t19_2.setGeometry(QtCore.QRect(748, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t19_2.setFont(font)
        self.pb_pf_t19_2.setObjectName("pb_pf_t19_2")
        self.pb_pf_t11_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t11_2.setGeometry(QtCore.QRect(437, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t11_2.setFont(font)
        self.pb_pf_t11_2.setObjectName("pb_pf_t11_2")
        self.pb_pf_t27_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t27_1.setGeometry(QtCore.QRect(1054, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t27_1.setFont(font)
        self.pb_pf_t27_1.setObjectName("pb_pf_t27_1")
        self.pb_pf_t11_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t11_4.setGeometry(QtCore.QRect(436, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t11_4.setFont(font)
        self.pb_pf_t11_4.setObjectName("pb_pf_t11_4")
        self.pb_pf_t30_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t30_3.setGeometry(QtCore.QRect(1170, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t30_3.setFont(font)
        self.pb_pf_t30_3.setObjectName("pb_pf_t30_3")
        self.pb_pf_t16_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t16_0.setGeometry(QtCore.QRect(631, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t16_0.setFont(font)
        self.pb_pf_t16_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t16_0.setObjectName("pb_pf_t16_0")
        self.lbl_fail_t26 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t26.setEnabled(True)
        self.lbl_fail_t26.setGeometry(QtCore.QRect(1012, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t26.setFont(font)
        self.lbl_fail_t26.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t26.setObjectName("lbl_fail_t26")
        self.lbl_fail_t14 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t14.setEnabled(True)
        self.lbl_fail_t14.setGeometry(QtCore.QRect(549, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t14.setFont(font)
        self.lbl_fail_t14.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t14.setObjectName("lbl_fail_t14")
        self.pb_pf_t28_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t28_4.setGeometry(QtCore.QRect(1089, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t28_4.setFont(font)
        self.pb_pf_t28_4.setObjectName("pb_pf_t28_4")
        self.pb_pf_t13_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t13_0.setGeometry(QtCore.QRect(514, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t13_0.setFont(font)
        self.pb_pf_t13_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t13_0.setObjectName("pb_pf_t13_0")
        self.sbLoopCount = QtWidgets.QSpinBox(self.tab_debug)
        self.sbLoopCount.setGeometry(QtCore.QRect(1024, 24, 90, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sbLoopCount.setFont(font)
        self.sbLoopCount.setMinimum(1)
        self.sbLoopCount.setMaximum(5000)
        self.sbLoopCount.setSingleStep(10)
        self.sbLoopCount.setObjectName("sbLoopCount")
        self.pb_pf_t9_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t9_4.setGeometry(QtCore.QRect(358, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t9_4.setFont(font)
        self.pb_pf_t9_4.setObjectName("pb_pf_t9_4")
        self.pb_pf_t28_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t28_0.setGeometry(QtCore.QRect(1092, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t28_0.setFont(font)
        self.pb_pf_t28_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t28_0.setObjectName("pb_pf_t28_0")
        self.pb_pf_t22_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t22_4.setGeometry(QtCore.QRect(863, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t22_4.setFont(font)
        self.pb_pf_t22_4.setObjectName("pb_pf_t22_4")
        self.pb_slot_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_slot_3.setGeometry(QtCore.QRect(1, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_slot_3.setFont(font)
        self.pb_slot_3.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_slot_3.setObjectName("pb_slot_3")
        self.pb_pf_t25_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t25_1.setGeometry(QtCore.QRect(978, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t25_1.setFont(font)
        self.pb_pf_t25_1.setObjectName("pb_pf_t25_1")
        self.pb_pf_t24_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t24_3.setGeometry(QtCore.QRect(939, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t24_3.setFont(font)
        self.pb_pf_t24_3.setObjectName("pb_pf_t24_3")
        self.pb_pf_t12_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t12_0.setGeometry(QtCore.QRect(475, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t12_0.setFont(font)
        self.pb_pf_t12_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t12_0.setObjectName("pb_pf_t12_0")
        self.pb_pf_t13_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t13_1.setGeometry(QtCore.QRect(514, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t13_1.setFont(font)
        self.pb_pf_t13_1.setObjectName("pb_pf_t13_1")
        self.pb_pf_t7_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t7_0.setGeometry(QtCore.QRect(280, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t7_0.setFont(font)
        self.pb_pf_t7_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t7_0.setObjectName("pb_pf_t7_0")
        self.pb_pf_t27_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t27_0.setGeometry(QtCore.QRect(1054, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t27_0.setFont(font)
        self.pb_pf_t27_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t27_0.setObjectName("pb_pf_t27_0")
        self.pb_pf_t2_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t2_2.setGeometry(QtCore.QRect(86, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t2_2.setFont(font)
        self.pb_pf_t2_2.setObjectName("pb_pf_t2_2")
        self.pb_pf_t11_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t11_0.setGeometry(QtCore.QRect(436, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t11_0.setFont(font)
        self.pb_pf_t11_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t11_0.setObjectName("pb_pf_t11_0")
        self.pb_pf_t21_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t21_3.setGeometry(QtCore.QRect(825, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t21_3.setFont(font)
        self.pb_pf_t21_3.setObjectName("pb_pf_t21_3")
        self.lbl_fail_t30 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t30.setEnabled(True)
        self.lbl_fail_t30.setGeometry(QtCore.QRect(1166, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t30.setFont(font)
        self.lbl_fail_t30.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t30.setObjectName("lbl_fail_t30")
        self.pb_pf_t10_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t10_1.setGeometry(QtCore.QRect(397, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t10_1.setFont(font)
        self.pb_pf_t10_1.setObjectName("pb_pf_t10_1")
        self.lbl_fail_t28 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t28.setEnabled(True)
        self.lbl_fail_t28.setGeometry(QtCore.QRect(1085, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t28.setFont(font)
        self.lbl_fail_t28.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t28.setObjectName("lbl_fail_t28")
        self.pb_pf_t10_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t10_0.setGeometry(QtCore.QRect(397, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t10_0.setFont(font)
        self.pb_pf_t10_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t10_0.setObjectName("pb_pf_t10_0")
        self.pb_pf_t27_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t27_2.setGeometry(QtCore.QRect(1055, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t27_2.setFont(font)
        self.pb_pf_t27_2.setObjectName("pb_pf_t27_2")
        self.btn_start = QtWidgets.QPushButton(self.tab_debug)
        self.btn_start.setEnabled(True)
        self.btn_start.setGeometry(QtCore.QRect(808, 22, 116, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_start.setFont(font)
        self.btn_start.setStyleSheet(" QPushButton {\n"
"    border-style: ridge;\n"
"     border: 2px solid DarkSlateGray;\n"
"     border-radius: 6px;\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
" }\n"
"\n"
" QPushButton:pressed {\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
" }\n"
"\n"
" QPushButton:!enabled {\n"
"     background-color:DarkGray;\n"
" }\n"
"")
        self.btn_start.setObjectName("btn_start")
        self.pb_pf_t8_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t8_2.setGeometry(QtCore.QRect(320, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t8_2.setFont(font)
        self.pb_pf_t8_2.setObjectName("pb_pf_t8_2")
        self.pb_pf_t15_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t15_1.setGeometry(QtCore.QRect(592, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t15_1.setFont(font)
        self.pb_pf_t15_1.setObjectName("pb_pf_t15_1")
        self.lbl_fail_t18 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t18.setEnabled(True)
        self.lbl_fail_t18.setGeometry(QtCore.QRect(703, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t18.setFont(font)
        self.lbl_fail_t18.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t18.setObjectName("lbl_fail_t18")
        self.pb_pf_t7_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t7_4.setGeometry(QtCore.QRect(280, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t7_4.setFont(font)
        self.pb_pf_t7_4.setObjectName("pb_pf_t7_4")
        self.pb_pf_t23_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t23_3.setGeometry(QtCore.QRect(901, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t23_3.setFont(font)
        self.pb_pf_t23_3.setObjectName("pb_pf_t23_3")
        self.pb_pf_t3_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t3_2.setGeometry(QtCore.QRect(125, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t3_2.setFont(font)
        self.pb_pf_t3_2.setObjectName("pb_pf_t3_2")
        self.pb_pf_t21_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t21_1.setGeometry(QtCore.QRect(825, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t21_1.setFont(font)
        self.pb_pf_t21_1.setObjectName("pb_pf_t21_1")
        self.lbl_fail_t20 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t20.setEnabled(True)
        self.lbl_fail_t20.setGeometry(QtCore.QRect(781, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t20.setFont(font)
        self.lbl_fail_t20.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t20.setObjectName("lbl_fail_t20")
        self.lbl_fail_t25 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t25.setEnabled(True)
        self.lbl_fail_t25.setGeometry(QtCore.QRect(974, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t25.setFont(font)
        self.lbl_fail_t25.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t25.setObjectName("lbl_fail_t25")
        self.pb_pf_t7_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t7_1.setGeometry(QtCore.QRect(280, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t7_1.setFont(font)
        self.pb_pf_t7_1.setObjectName("pb_pf_t7_1")
        self.pb_pf_t28_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t28_2.setGeometry(QtCore.QRect(1090, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t28_2.setFont(font)
        self.pb_pf_t28_2.setObjectName("pb_pf_t28_2")
        self.pb_pf_t4_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t4_2.setGeometry(QtCore.QRect(164, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t4_2.setFont(font)
        self.pb_pf_t4_2.setObjectName("pb_pf_t4_2")
        self.pb_pf_t17_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t17_1.setGeometry(QtCore.QRect(669, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t17_1.setFont(font)
        self.pb_pf_t17_1.setObjectName("pb_pf_t17_1")
        self.lbl_fail_t22 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t22.setEnabled(True)
        self.lbl_fail_t22.setGeometry(QtCore.QRect(858, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t22.setFont(font)
        self.lbl_fail_t22.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t22.setObjectName("lbl_fail_t22")
        self.pb_pf_t1_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t1_4.setGeometry(QtCore.QRect(45, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t1_4.setFont(font)
        self.pb_pf_t1_4.setObjectName("pb_pf_t1_4")
        self.pb_pf_t27_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t27_3.setGeometry(QtCore.QRect(1054, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t27_3.setFont(font)
        self.pb_pf_t27_3.setObjectName("pb_pf_t27_3")
        self.cbLoop = QtWidgets.QCheckBox(self.tab_debug)
        self.cbLoop.setGeometry(QtCore.QRect(938, 28, 81, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cbLoop.setFont(font)
        self.cbLoop.setObjectName("cbLoop")
        self.lbl_fail_t2 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t2.setEnabled(True)
        self.lbl_fail_t2.setGeometry(QtCore.QRect(80, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t2.setFont(font)
        self.lbl_fail_t2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t2.setObjectName("lbl_fail_t2")
        self.pb_pf_t3_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t3_1.setGeometry(QtCore.QRect(124, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t3_1.setFont(font)
        self.pb_pf_t3_1.setObjectName("pb_pf_t3_1")
        self.pb_pf_t25_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t25_2.setGeometry(QtCore.QRect(979, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t25_2.setFont(font)
        self.pb_pf_t25_2.setObjectName("pb_pf_t25_2")
        self.pb_pf_t24_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t24_2.setGeometry(QtCore.QRect(940, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t24_2.setFont(font)
        self.pb_pf_t24_2.setObjectName("pb_pf_t24_2")
        self.lbl_fail_t7 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t7.setEnabled(True)
        self.lbl_fail_t7.setGeometry(QtCore.QRect(274, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t7.setFont(font)
        self.lbl_fail_t7.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t7.setObjectName("lbl_fail_t7")
        self.lbl_fail_t17 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t17.setEnabled(True)
        self.lbl_fail_t17.setGeometry(QtCore.QRect(665, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t17.setFont(font)
        self.lbl_fail_t17.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t17.setObjectName("lbl_fail_t17")
        self.pb_pf_t25_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t25_3.setGeometry(QtCore.QRect(978, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t25_3.setFont(font)
        self.pb_pf_t25_3.setObjectName("pb_pf_t25_3")
        self.lbl_fail_t29 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t29.setEnabled(True)
        self.lbl_fail_t29.setGeometry(QtCore.QRect(1125, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t29.setFont(font)
        self.lbl_fail_t29.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t29.setObjectName("lbl_fail_t29")
        self.pb_slot_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_slot_1.setGeometry(QtCore.QRect(1, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_slot_1.setFont(font)
        self.pb_slot_1.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_slot_1.setObjectName("pb_slot_1")
        self.pb_pf_t19_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t19_3.setGeometry(QtCore.QRect(747, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t19_3.setFont(font)
        self.pb_pf_t19_3.setObjectName("pb_pf_t19_3")
        self.pb_pf_t19_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t19_0.setGeometry(QtCore.QRect(747, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t19_0.setFont(font)
        self.pb_pf_t19_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t19_0.setObjectName("pb_pf_t19_0")
        self.pb_pf_t29_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t29_3.setGeometry(QtCore.QRect(1129, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t29_3.setFont(font)
        self.pb_pf_t29_3.setObjectName("pb_pf_t29_3")
        self.lbl_fail_t19 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t19.setEnabled(True)
        self.lbl_fail_t19.setGeometry(QtCore.QRect(741, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t19.setFont(font)
        self.lbl_fail_t19.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t19.setObjectName("lbl_fail_t19")
        self.pb_pf_t4_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t4_4.setGeometry(QtCore.QRect(163, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t4_4.setFont(font)
        self.pb_pf_t4_4.setObjectName("pb_pf_t4_4")
        self.pb_pf_t2_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t2_1.setGeometry(QtCore.QRect(85, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t2_1.setFont(font)
        self.pb_pf_t2_1.setObjectName("pb_pf_t2_1")
        self.lbl_fail_t1 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t1.setEnabled(True)
        self.lbl_fail_t1.setGeometry(QtCore.QRect(41, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t1.setFont(font)
        self.lbl_fail_t1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t1.setObjectName("lbl_fail_t1")
        self.pb_pf_t20_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t20_0.setGeometry(QtCore.QRect(786, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t20_0.setFont(font)
        self.pb_pf_t20_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t20_0.setObjectName("pb_pf_t20_0")
        self.lbl_fail_t24 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t24.setEnabled(True)
        self.lbl_fail_t24.setGeometry(QtCore.QRect(935, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t24.setFont(font)
        self.lbl_fail_t24.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t24.setObjectName("lbl_fail_t24")
        self.pb_pf_t17_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t17_4.setGeometry(QtCore.QRect(669, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t17_4.setFont(font)
        self.pb_pf_t17_4.setObjectName("pb_pf_t17_4")
        self.pb_pf_t19_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t19_4.setGeometry(QtCore.QRect(747, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t19_4.setFont(font)
        self.pb_pf_t19_4.setObjectName("pb_pf_t19_4")
        self.pb_pf_t16_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t16_1.setGeometry(QtCore.QRect(631, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t16_1.setFont(font)
        self.pb_pf_t16_1.setObjectName("pb_pf_t16_1")
        self.pb_pf_t15_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t15_0.setGeometry(QtCore.QRect(592, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t15_0.setFont(font)
        self.pb_pf_t15_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t15_0.setObjectName("pb_pf_t15_0")
        self.pb_pf_t12_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t12_1.setGeometry(QtCore.QRect(475, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t12_1.setFont(font)
        self.pb_pf_t12_1.setObjectName("pb_pf_t12_1")
        self.pb_pf_t24_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t24_4.setGeometry(QtCore.QRect(939, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t24_4.setFont(font)
        self.pb_pf_t24_4.setObjectName("pb_pf_t24_4")
        self.pb_pf_t21_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t21_4.setGeometry(QtCore.QRect(825, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t21_4.setFont(font)
        self.pb_pf_t21_4.setObjectName("pb_pf_t21_4")
        self.pb_pf_t20_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t20_2.setGeometry(QtCore.QRect(787, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t20_2.setFont(font)
        self.pb_pf_t20_2.setObjectName("pb_pf_t20_2")
        self.pb_pf_t10_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t10_2.setGeometry(QtCore.QRect(398, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t10_2.setFont(font)
        self.pb_pf_t10_2.setObjectName("pb_pf_t10_2")
        self.lbl_fail_t16 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t16.setEnabled(True)
        self.lbl_fail_t16.setGeometry(QtCore.QRect(626, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t16.setFont(font)
        self.lbl_fail_t16.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t16.setObjectName("lbl_fail_t16")
        self.pb_pf_t8_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t8_3.setGeometry(QtCore.QRect(319, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t8_3.setFont(font)
        self.pb_pf_t8_3.setObjectName("pb_pf_t8_3")
        self.lbl_fail_t8 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t8.setEnabled(True)
        self.lbl_fail_t8.setGeometry(QtCore.QRect(312, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t8.setFont(font)
        self.lbl_fail_t8.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t8.setObjectName("lbl_fail_t8")
        self.pb_pf_t30_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t30_4.setGeometry(QtCore.QRect(1170, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t30_4.setFont(font)
        self.pb_pf_t30_4.setObjectName("pb_pf_t30_4")
        self.pb_pf_t4_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t4_0.setGeometry(QtCore.QRect(163, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t4_0.setFont(font)
        self.pb_pf_t4_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t4_0.setObjectName("pb_pf_t4_0")
        self.pb_pf_t30_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t30_0.setGeometry(QtCore.QRect(1170, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t30_0.setFont(font)
        self.pb_pf_t30_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t30_0.setObjectName("pb_pf_t30_0")
        self.pb_pf_t3_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t3_3.setGeometry(QtCore.QRect(124, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t3_3.setFont(font)
        self.pb_pf_t3_3.setObjectName("pb_pf_t3_3")
        self.pb_pf_t26_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t26_0.setGeometry(QtCore.QRect(1016, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t26_0.setFont(font)
        self.pb_pf_t26_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t26_0.setObjectName("pb_pf_t26_0")
        self.pb_pf_t7_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t7_3.setGeometry(QtCore.QRect(280, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t7_3.setFont(font)
        self.pb_pf_t7_3.setObjectName("pb_pf_t7_3")
        self.lbl_fail_t13 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t13.setEnabled(True)
        self.lbl_fail_t13.setGeometry(QtCore.QRect(508, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t13.setFont(font)
        self.lbl_fail_t13.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t13.setObjectName("lbl_fail_t13")
        self.pb_pf_t29_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t29_1.setGeometry(QtCore.QRect(1129, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t29_1.setFont(font)
        self.pb_pf_t29_1.setObjectName("pb_pf_t29_1")
        self.lbl_fail_t4 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t4.setEnabled(True)
        self.lbl_fail_t4.setGeometry(QtCore.QRect(157, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t4.setFont(font)
        self.lbl_fail_t4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t4.setObjectName("lbl_fail_t4")
        self.pb_pf_t3_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t3_4.setGeometry(QtCore.QRect(124, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t3_4.setFont(font)
        self.pb_pf_t3_4.setObjectName("pb_pf_t3_4")
        self.pb_pf_t26_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t26_4.setGeometry(QtCore.QRect(1016, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t26_4.setFont(font)
        self.pb_pf_t26_4.setObjectName("pb_pf_t26_4")
        self.pb_pf_t6_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t6_4.setGeometry(QtCore.QRect(241, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t6_4.setFont(font)
        self.pb_pf_t6_4.setObjectName("pb_pf_t6_4")
        self.pb_pf_t1_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t1_1.setGeometry(QtCore.QRect(45, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t1_1.setFont(font)
        self.pb_pf_t1_1.setObjectName("pb_pf_t1_1")
        self.pb_pf_t10_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t10_3.setGeometry(QtCore.QRect(397, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t10_3.setFont(font)
        self.pb_pf_t10_3.setObjectName("pb_pf_t10_3")
        self.pb_pf_t23_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t23_4.setGeometry(QtCore.QRect(901, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t23_4.setFont(font)
        self.pb_pf_t23_4.setObjectName("pb_pf_t23_4")
        self.pb_pf_t9_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t9_0.setGeometry(QtCore.QRect(358, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t9_0.setFont(font)
        self.pb_pf_t9_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t9_0.setObjectName("pb_pf_t9_0")
        self.pb_pf_t23_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t23_1.setGeometry(QtCore.QRect(901, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t23_1.setFont(font)
        self.pb_pf_t23_1.setObjectName("pb_pf_t23_1")
        self.pb_pf_t23_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t23_2.setGeometry(QtCore.QRect(902, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t23_2.setFont(font)
        self.pb_pf_t23_2.setObjectName("pb_pf_t23_2")
        self.pb_pf_t28_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t28_3.setGeometry(QtCore.QRect(1089, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t28_3.setFont(font)
        self.pb_pf_t28_3.setObjectName("pb_pf_t28_3")
        self.pb_pf_t14_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t14_2.setGeometry(QtCore.QRect(554, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t14_2.setFont(font)
        self.pb_pf_t14_2.setObjectName("pb_pf_t14_2")
        self.pb_pf_t9_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t9_3.setGeometry(QtCore.QRect(358, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t9_3.setFont(font)
        self.pb_pf_t9_3.setObjectName("pb_pf_t9_3")
        self.pb_pf_t9_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t9_1.setGeometry(QtCore.QRect(358, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t9_1.setFont(font)
        self.pb_pf_t9_1.setObjectName("pb_pf_t9_1")
        self.pb_pf_t29_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t29_0.setGeometry(QtCore.QRect(1130, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t29_0.setFont(font)
        self.pb_pf_t29_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t29_0.setObjectName("pb_pf_t29_0")
        self.pb_pf_t9_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t9_2.setGeometry(QtCore.QRect(359, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t9_2.setFont(font)
        self.pb_pf_t9_2.setObjectName("pb_pf_t9_2")
        self.pb_pf_t5_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t5_1.setGeometry(QtCore.QRect(202, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t5_1.setFont(font)
        self.pb_pf_t5_1.setObjectName("pb_pf_t5_1")
        self.pb_pf_t22_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t22_2.setGeometry(QtCore.QRect(864, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t22_2.setFont(font)
        self.pb_pf_t22_2.setObjectName("pb_pf_t22_2")
        self.pb_pf_t22_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t22_0.setGeometry(QtCore.QRect(863, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t22_0.setFont(font)
        self.pb_pf_t22_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t22_0.setObjectName("pb_pf_t22_0")
        self.pb_pf_t17_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t17_3.setGeometry(QtCore.QRect(669, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t17_3.setFont(font)
        self.pb_pf_t17_3.setObjectName("pb_pf_t17_3")
        self.pb_pf_t29_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t29_4.setGeometry(QtCore.QRect(1129, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t29_4.setFont(font)
        self.pb_pf_t29_4.setObjectName("pb_pf_t29_4")
        self.pb_pf_t4_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t4_1.setGeometry(QtCore.QRect(163, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t4_1.setFont(font)
        self.pb_pf_t4_1.setObjectName("pb_pf_t4_1")
        self.pb_pf_t5_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t5_2.setGeometry(QtCore.QRect(203, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t5_2.setFont(font)
        self.pb_pf_t5_2.setObjectName("pb_pf_t5_2")
        self.pb_pf_t26_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t26_2.setGeometry(QtCore.QRect(1017, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t26_2.setFont(font)
        self.pb_pf_t26_2.setObjectName("pb_pf_t26_2")
        self.lbl_fail_t21 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t21.setEnabled(True)
        self.lbl_fail_t21.setGeometry(QtCore.QRect(821, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t21.setFont(font)
        self.lbl_fail_t21.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t21.setObjectName("lbl_fail_t21")
        self.pb_pf_t12_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t12_4.setGeometry(QtCore.QRect(475, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t12_4.setFont(font)
        self.pb_pf_t12_4.setObjectName("pb_pf_t12_4")
        self.lbl_fail_t3 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t3.setEnabled(True)
        self.lbl_fail_t3.setGeometry(QtCore.QRect(118, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t3.setFont(font)
        self.lbl_fail_t3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t3.setObjectName("lbl_fail_t3")
        self.pb_pf_t18_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t18_2.setGeometry(QtCore.QRect(709, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t18_2.setFont(font)
        self.pb_pf_t18_2.setObjectName("pb_pf_t18_2")
        self.pb_pf_t16_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t16_3.setGeometry(QtCore.QRect(631, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t16_3.setFont(font)
        self.pb_pf_t16_3.setObjectName("pb_pf_t16_3")
        self.lbl_fail_t11 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t11.setEnabled(True)
        self.lbl_fail_t11.setGeometry(QtCore.QRect(430, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t11.setFont(font)
        self.lbl_fail_t11.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t11.setObjectName("lbl_fail_t11")
        self.pb_slot_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_slot_4.setGeometry(QtCore.QRect(1, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_slot_4.setFont(font)
        self.pb_slot_4.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_slot_4.setObjectName("pb_slot_4")
        self.pb_pf_t2_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t2_0.setGeometry(QtCore.QRect(85, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t2_0.setFont(font)
        self.pb_pf_t2_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t2_0.setObjectName("pb_pf_t2_0")
        self.pb_pf_t8_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t8_4.setGeometry(QtCore.QRect(319, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t8_4.setFont(font)
        self.pb_pf_t8_4.setObjectName("pb_pf_t8_4")
        self.pb_pf_t1_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t1_3.setGeometry(QtCore.QRect(45, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t1_3.setFont(font)
        self.pb_pf_t1_3.setObjectName("pb_pf_t1_3")
        self.pb_pf_t2_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t2_3.setGeometry(QtCore.QRect(85, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t2_3.setFont(font)
        self.pb_pf_t2_3.setObjectName("pb_pf_t2_3")
        self.pb_pf_t20_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t20_4.setGeometry(QtCore.QRect(786, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t20_4.setFont(font)
        self.pb_pf_t20_4.setObjectName("pb_pf_t20_4")
        self.pb_pf_t6_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t6_3.setGeometry(QtCore.QRect(241, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t6_3.setFont(font)
        self.pb_pf_t6_3.setObjectName("pb_pf_t6_3")
        self.pb_pf_t25_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t25_0.setGeometry(QtCore.QRect(978, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t25_0.setFont(font)
        self.pb_pf_t25_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t25_0.setObjectName("pb_pf_t25_0")
        self.lbl_fail_t5 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t5.setEnabled(True)
        self.lbl_fail_t5.setGeometry(QtCore.QRect(196, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t5.setFont(font)
        self.lbl_fail_t5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t5.setObjectName("lbl_fail_t5")
        self.lbl_fail_t15 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t15.setEnabled(True)
        self.lbl_fail_t15.setGeometry(QtCore.QRect(587, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t15.setFont(font)
        self.lbl_fail_t15.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t15.setObjectName("lbl_fail_t15")
        self.pb_pf_t22_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t22_1.setGeometry(QtCore.QRect(863, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t22_1.setFont(font)
        self.pb_pf_t22_1.setObjectName("pb_pf_t22_1")
        self.pb_pf_t5_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t5_4.setGeometry(QtCore.QRect(202, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t5_4.setFont(font)
        self.pb_pf_t5_4.setObjectName("pb_pf_t5_4")
        self.pb_pf_t4_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t4_3.setGeometry(QtCore.QRect(163, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t4_3.setFont(font)
        self.pb_pf_t4_3.setObjectName("pb_pf_t4_3")
        self.lbl_fail_t10 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t10.setEnabled(True)
        self.lbl_fail_t10.setGeometry(QtCore.QRect(392, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t10.setFont(font)
        self.lbl_fail_t10.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t10.setObjectName("lbl_fail_t10")
        self.pb_pf_t15_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t15_4.setGeometry(QtCore.QRect(592, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t15_4.setFont(font)
        self.pb_pf_t15_4.setObjectName("pb_pf_t15_4")
        self.pb_pf_t8_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t8_0.setGeometry(QtCore.QRect(319, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t8_0.setFont(font)
        self.pb_pf_t8_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t8_0.setObjectName("pb_pf_t8_0")
        self.pb_pf_t3_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t3_0.setGeometry(QtCore.QRect(124, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t3_0.setFont(font)
        self.pb_pf_t3_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t3_0.setObjectName("pb_pf_t3_0")
        self.pb_pf_t15_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t15_2.setGeometry(QtCore.QRect(593, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t15_2.setFont(font)
        self.pb_pf_t15_2.setObjectName("pb_pf_t15_2")
        self.lbl_fail_t27 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t27.setEnabled(True)
        self.lbl_fail_t27.setGeometry(QtCore.QRect(1050, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t27.setFont(font)
        self.lbl_fail_t27.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t27.setObjectName("lbl_fail_t27")
        self.pb_pf_t16_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t16_2.setGeometry(QtCore.QRect(632, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t16_2.setFont(font)
        self.pb_pf_t16_2.setObjectName("pb_pf_t16_2")
        self.pb_pf_t14_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t14_0.setGeometry(QtCore.QRect(553, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t14_0.setFont(font)
        self.pb_pf_t14_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t14_0.setObjectName("pb_pf_t14_0")
        self.pb_pf_t16_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t16_4.setGeometry(QtCore.QRect(631, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t16_4.setFont(font)
        self.pb_pf_t16_4.setObjectName("pb_pf_t16_4")
        self.pb_pf_t22_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t22_3.setGeometry(QtCore.QRect(863, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t22_3.setFont(font)
        self.pb_pf_t22_3.setObjectName("pb_pf_t22_3")
        self.pb_pf_t13_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t13_3.setGeometry(QtCore.QRect(514, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t13_3.setFont(font)
        self.pb_pf_t13_3.setObjectName("pb_pf_t13_3")
        self.pb_pf_t14_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t14_3.setGeometry(QtCore.QRect(553, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t14_3.setFont(font)
        self.pb_pf_t14_3.setObjectName("pb_pf_t14_3")
        self.lbl_fail_t6 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t6.setEnabled(True)
        self.lbl_fail_t6.setGeometry(QtCore.QRect(235, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t6.setFont(font)
        self.lbl_fail_t6.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t6.setObjectName("lbl_fail_t6")
        self.lbl_fail_t9 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t9.setEnabled(True)
        self.lbl_fail_t9.setGeometry(QtCore.QRect(352, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t9.setFont(font)
        self.lbl_fail_t9.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t9.setObjectName("lbl_fail_t9")
        self.pb_pf_t30_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t30_2.setGeometry(QtCore.QRect(1171, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t30_2.setFont(font)
        self.pb_pf_t30_2.setObjectName("pb_pf_t30_2")
        self.pb_pf_t11_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t11_1.setGeometry(QtCore.QRect(436, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t11_1.setFont(font)
        self.pb_pf_t11_1.setObjectName("pb_pf_t11_1")
        self.pb_pf_t30_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t30_1.setGeometry(QtCore.QRect(1170, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t30_1.setFont(font)
        self.pb_pf_t30_1.setObjectName("pb_pf_t30_1")
        self.pb_pf_t26_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t26_3.setGeometry(QtCore.QRect(1016, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t26_3.setFont(font)
        self.pb_pf_t26_3.setObjectName("pb_pf_t26_3")
        self.pb_pf_t13_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t13_2.setGeometry(QtCore.QRect(515, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t13_2.setFont(font)
        self.pb_pf_t13_2.setObjectName("pb_pf_t13_2")
        self.pb_pf_t15_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t15_3.setGeometry(QtCore.QRect(592, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t15_3.setFont(font)
        self.pb_pf_t15_3.setObjectName("pb_pf_t15_3")
        self.pb_pf_t27_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t27_4.setGeometry(QtCore.QRect(1054, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t27_4.setFont(font)
        self.pb_pf_t27_4.setObjectName("pb_pf_t27_4")
        self.pb_pf_t13_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t13_4.setGeometry(QtCore.QRect(514, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t13_4.setFont(font)
        self.pb_pf_t13_4.setObjectName("pb_pf_t13_4")
        self.pb_pf_t6_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t6_0.setGeometry(QtCore.QRect(241, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t6_0.setFont(font)
        self.pb_pf_t6_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t6_0.setObjectName("pb_pf_t6_0")
        self.pb_pf_t19_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t19_1.setGeometry(QtCore.QRect(747, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t19_1.setFont(font)
        self.pb_pf_t19_1.setObjectName("pb_pf_t19_1")
        self.pb_pf_t12_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t12_3.setGeometry(QtCore.QRect(475, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t12_3.setFont(font)
        self.pb_pf_t12_3.setObjectName("pb_pf_t12_3")
        self.pb_pf_t18_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t18_3.setGeometry(QtCore.QRect(708, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t18_3.setFont(font)
        self.pb_pf_t18_3.setObjectName("pb_pf_t18_3")
        self.pb_pf_t20_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t20_3.setGeometry(QtCore.QRect(786, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t20_3.setFont(font)
        self.pb_pf_t20_3.setObjectName("pb_pf_t20_3")
        self.pb_pf_t5_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t5_0.setGeometry(QtCore.QRect(202, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t5_0.setFont(font)
        self.pb_pf_t5_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t5_0.setObjectName("pb_pf_t5_0")
        self.pb_pf_t17_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t17_2.setGeometry(QtCore.QRect(670, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t17_2.setFont(font)
        self.pb_pf_t17_2.setObjectName("pb_pf_t17_2")
        self.pb_pf_t1_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t1_2.setGeometry(QtCore.QRect(46, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t1_2.setFont(font)
        self.pb_pf_t1_2.setObjectName("pb_pf_t1_2")
        self.pb_pf_t6_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t6_1.setGeometry(QtCore.QRect(241, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t6_1.setFont(font)
        self.pb_pf_t6_1.setObjectName("pb_pf_t6_1")
        self.pb_pf_t1_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t1_0.setGeometry(QtCore.QRect(45, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t1_0.setFont(font)
        self.pb_pf_t1_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t1_0.setObjectName("pb_pf_t1_0")
        self.lbl_fail_t23 = QtWidgets.QLabel(self.tab_debug)
        self.lbl_fail_t23.setEnabled(True)
        self.lbl_fail_t23.setGeometry(QtCore.QRect(897, 216, 47, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fail_t23.setFont(font)
        self.lbl_fail_t23.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fail_t23.setObjectName("lbl_fail_t23")
        self.pb_pf_t24_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t24_1.setGeometry(QtCore.QRect(939, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t24_1.setFont(font)
        self.pb_pf_t24_1.setObjectName("pb_pf_t24_1")
        self.pb_pf_t11_3 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t11_3.setGeometry(QtCore.QRect(436, 166, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t11_3.setFont(font)
        self.pb_pf_t11_3.setObjectName("pb_pf_t11_3")
        self.pb_pf_t8_1 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t8_1.setGeometry(QtCore.QRect(319, 114, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t8_1.setFont(font)
        self.pb_pf_t8_1.setObjectName("pb_pf_t8_1")
        self.pb_pf_t12_2 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t12_2.setGeometry(QtCore.QRect(476, 140, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t12_2.setFont(font)
        self.pb_pf_t12_2.setObjectName("pb_pf_t12_2")
        self.pb_pf_t21_0 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t21_0.setGeometry(QtCore.QRect(825, 88, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t21_0.setFont(font)
        self.pb_pf_t21_0.setStyleSheet(" QPushButton{\n"
"     border-width: 1px;\n"
"     border-style: solid;\n"
"     border-color: blue;\n"
"}")
        self.pb_pf_t21_0.setObjectName("pb_pf_t21_0")
        self.pb_pf_t2_4 = QtWidgets.QPushButton(self.tab_debug)
        self.pb_pf_t2_4.setGeometry(QtCore.QRect(85, 192, 40, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_pf_t2_4.setFont(font)
        self.pb_pf_t2_4.setObjectName("pb_pf_t2_4")
        self.twInfoBoard.addTab(self.tab_debug, "")
        self.template_frame = QtWidgets.QFrame(self.centralwidget)
        self.template_frame.setGeometry(QtCore.QRect(2, 106, 1280, 579))
        self.template_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.template_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.template_frame.setObjectName("template_frame")
        self.lbl_product.raise_()
        self.lbl_date_time.raise_()
        self.lbl_grn.raise_()
        self.lbl_lbl_product.raise_()
        self.lbl_lbl_grn.raise_()
        self.btn_back.raise_()
        self.twInfoBoard.raise_()
        self.template_frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.statusbar.setFont(font)
        self.statusbar.setStyleSheet("QStatusBar{\n"
"    padding-left:8px;\n"
"    color:black;\n"
"    font-weight:bold;\n"
"}")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.twInfoBoard.setCurrentIndex(0)
        self.btn_start.clicked.connect(MainWindow.btn_soft_start_click)
        self.cbLoop.clicked.connect(MainWindow.cb_Loop_click)
        self.btn_back.clicked.connect(MainWindow.btn_back_click)
        self.btn_lbl_start.clicked.connect(MainWindow.btn_soft_start_click)
        self.twInfoBoard.tabBarClicked['int'].connect(MainWindow.twInfoBoard_click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Generic Tester"))
        self.lbl_lbl_grn.setText(_translate("MainWindow", "GRN #:"))
        self.lbl_lbl_product.setText(_translate("MainWindow", "Product:"))
        self.lbl_product.setText(_translate("MainWindow", "?"))
        self.lbl_grn.setText(_translate("MainWindow", "?"))
        self.lbl_date_time.setText(_translate("MainWindow", "_"))
        self.btn_back.setText(_translate("MainWindow", "BACK"))
        self.lbl_lbl_units_fail.setText(_translate("MainWindow", "Units fail :"))
        self.lbl_lbl_units_tested.setText(_translate("MainWindow", "Units tested :"))
        self.lbl_units_pass.setText(_translate("MainWindow", "0"))
        self.lbl_lbl_units_pass.setText(_translate("MainWindow", "Units pass :"))
        self.lbl_units_fail.setText(_translate("MainWindow", "0"))
        self.lbl_units_tested.setText(_translate("MainWindow", "0"))
        self.btn_lbl_start.setText(_translate("MainWindow", "START"))
        self.twInfoBoard.setTabText(self.twInfoBoard.indexOf(self.tab_info), _translate("MainWindow", "Test"))
        self.pb_pf_t17_0.setText(_translate("MainWindow", "17"))
        self.pb_pf_t26_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t5_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t28_1.setText(_translate("MainWindow", "0"))
        self.pb_slot_2.setText(_translate("MainWindow", "S2"))
        self.pb_pf_t18_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t21_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t29_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t14_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t23_0.setText(_translate("MainWindow", "23"))
        self.pb_pf_t6_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t18_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t14_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t25_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t10_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t18_0.setText(_translate("MainWindow", "18"))
        self.pb_pf_t24_0.setText(_translate("MainWindow", "24"))
        self.lbl_fail_t12.setText(_translate("MainWindow", "0"))
        self.pb_pf_t7_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t20_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t19_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t11_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t27_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t11_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t30_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t16_0.setText(_translate("MainWindow", "16"))
        self.lbl_fail_t26.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t14.setText(_translate("MainWindow", "0"))
        self.pb_pf_t28_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t13_0.setText(_translate("MainWindow", "13"))
        self.pb_pf_t9_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t28_0.setText(_translate("MainWindow", "28"))
        self.pb_pf_t22_4.setText(_translate("MainWindow", "0"))
        self.pb_slot_3.setText(_translate("MainWindow", "S3"))
        self.pb_pf_t25_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t24_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t12_0.setText(_translate("MainWindow", "12"))
        self.pb_pf_t13_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t7_0.setText(_translate("MainWindow", "7"))
        self.pb_pf_t27_0.setText(_translate("MainWindow", "27"))
        self.pb_pf_t2_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t11_0.setText(_translate("MainWindow", "11"))
        self.pb_pf_t21_3.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t30.setText(_translate("MainWindow", "0"))
        self.pb_pf_t10_1.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t28.setText(_translate("MainWindow", "0"))
        self.pb_pf_t10_0.setText(_translate("MainWindow", "10"))
        self.pb_pf_t27_2.setText(_translate("MainWindow", "0"))
        self.btn_start.setText(_translate("MainWindow", "START"))
        self.pb_pf_t8_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t15_1.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t18.setText(_translate("MainWindow", "0"))
        self.pb_pf_t7_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t23_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t3_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t21_1.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t20.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t25.setText(_translate("MainWindow", "0"))
        self.pb_pf_t7_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t28_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t4_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t17_1.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t22.setText(_translate("MainWindow", "0"))
        self.pb_pf_t1_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t27_3.setText(_translate("MainWindow", "0"))
        self.cbLoop.setText(_translate("MainWindow", "Loops"))
        self.lbl_fail_t2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t3_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t25_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t24_2.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t7.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t17.setText(_translate("MainWindow", "0"))
        self.pb_pf_t25_3.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t29.setText(_translate("MainWindow", "0"))
        self.pb_slot_1.setText(_translate("MainWindow", "S1"))
        self.pb_pf_t19_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t19_0.setText(_translate("MainWindow", "19"))
        self.pb_pf_t29_3.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t19.setText(_translate("MainWindow", "0"))
        self.pb_pf_t4_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t2_1.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t20_0.setText(_translate("MainWindow", "20"))
        self.lbl_fail_t24.setText(_translate("MainWindow", "0"))
        self.pb_pf_t17_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t19_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t16_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t15_0.setText(_translate("MainWindow", "15"))
        self.pb_pf_t12_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t24_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t21_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t20_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t10_2.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t16.setText(_translate("MainWindow", "0"))
        self.pb_pf_t8_3.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t8.setText(_translate("MainWindow", "0"))
        self.pb_pf_t30_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t4_0.setText(_translate("MainWindow", "4"))
        self.pb_pf_t30_0.setText(_translate("MainWindow", "30"))
        self.pb_pf_t3_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t26_0.setText(_translate("MainWindow", "26"))
        self.pb_pf_t7_3.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t13.setText(_translate("MainWindow", "0"))
        self.pb_pf_t29_1.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t3_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t26_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t6_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t1_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t10_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t23_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t9_0.setText(_translate("MainWindow", "9"))
        self.pb_pf_t23_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t23_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t28_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t14_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t9_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t9_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t29_0.setText(_translate("MainWindow", "29"))
        self.pb_pf_t9_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t5_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t22_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t22_0.setText(_translate("MainWindow", "22"))
        self.pb_pf_t17_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t29_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t4_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t5_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t26_2.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t21.setText(_translate("MainWindow", "0"))
        self.pb_pf_t12_4.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t18_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t16_3.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t11.setText(_translate("MainWindow", "0"))
        self.pb_slot_4.setText(_translate("MainWindow", "S4"))
        self.pb_pf_t2_0.setText(_translate("MainWindow", "2"))
        self.pb_pf_t8_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t1_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t2_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t20_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t6_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t25_0.setText(_translate("MainWindow", "25"))
        self.lbl_fail_t5.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t15.setText(_translate("MainWindow", "0"))
        self.pb_pf_t22_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t5_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t4_3.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t10.setText(_translate("MainWindow", "0"))
        self.pb_pf_t15_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t8_0.setText(_translate("MainWindow", "8"))
        self.pb_pf_t3_0.setText(_translate("MainWindow", "3"))
        self.pb_pf_t15_2.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t27.setText(_translate("MainWindow", "0"))
        self.pb_pf_t16_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t14_0.setText(_translate("MainWindow", "14"))
        self.pb_pf_t16_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t22_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t13_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t14_3.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t6.setText(_translate("MainWindow", "0"))
        self.lbl_fail_t9.setText(_translate("MainWindow", "0"))
        self.pb_pf_t30_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t11_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t30_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t26_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t13_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t15_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t27_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t13_4.setText(_translate("MainWindow", "0"))
        self.pb_pf_t6_0.setText(_translate("MainWindow", "6"))
        self.pb_pf_t19_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t12_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t18_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t20_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t5_0.setText(_translate("MainWindow", "5"))
        self.pb_pf_t17_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t1_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t6_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t1_0.setText(_translate("MainWindow", "1"))
        self.lbl_fail_t23.setText(_translate("MainWindow", "0"))
        self.pb_pf_t24_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t11_3.setText(_translate("MainWindow", "0"))
        self.pb_pf_t8_1.setText(_translate("MainWindow", "0"))
        self.pb_pf_t12_2.setText(_translate("MainWindow", "0"))
        self.pb_pf_t21_0.setText(_translate("MainWindow", "21"))
        self.pb_pf_t2_4.setText(_translate("MainWindow", "0"))
        self.twInfoBoard.setTabText(self.twInfoBoard.indexOf(self.tab_debug), _translate("MainWindow", "Debug"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
