# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 't_04851_ASSM.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1250, 556)
        self.pb_3_14 = QtWidgets.QPushButton(Frame)
        self.pb_3_14.setGeometry(QtCore.QRect(900, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_14.setFont(font)
        self.pb_3_14.setObjectName("pb_3_14")
        self.pb_4_21 = QtWidgets.QPushButton(Frame)
        self.pb_4_21.setGeometry(QtCore.QRect(1030, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_21.setFont(font)
        self.pb_4_21.setObjectName("pb_4_21")
        self.pb_4_29 = QtWidgets.QPushButton(Frame)
        self.pb_4_29.setGeometry(QtCore.QRect(1176, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_29.setFont(font)
        self.pb_4_29.setObjectName("pb_4_29")
        self.pb_3_18 = QtWidgets.QPushButton(Frame)
        self.pb_3_18.setGeometry(QtCore.QRect(972, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_18.setFont(font)
        self.pb_3_18.setObjectName("pb_3_18")
        self.pb_4_15 = QtWidgets.QPushButton(Frame)
        self.pb_4_15.setGeometry(QtCore.QRect(921, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_15.setFont(font)
        self.pb_4_15.setObjectName("pb_4_15")
        self.line = QtWidgets.QFrame(Frame)
        self.line.setGeometry(QtCore.QRect(614, 8, 16, 539))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pb_2_2 = QtWidgets.QPushButton(Frame)
        self.pb_2_2.setGeometry(QtCore.QRect(62, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_2.setFont(font)
        self.pb_2_2.setObjectName("pb_2_2")
        self.pb_2_21 = QtWidgets.QPushButton(Frame)
        self.pb_2_21.setGeometry(QtCore.QRect(400, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_21.setFont(font)
        self.pb_2_21.setObjectName("pb_2_21")
        self.pb_3_6 = QtWidgets.QPushButton(Frame)
        self.pb_3_6.setGeometry(QtCore.QRect(754, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_6.setFont(font)
        self.pb_3_6.setObjectName("pb_3_6")
        self.pb_2_10 = QtWidgets.QPushButton(Frame)
        self.pb_2_10.setGeometry(QtCore.QRect(204, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_10.setFont(font)
        self.pb_2_10.setObjectName("pb_2_10")
        self.pb_1_1 = QtWidgets.QPushButton(Frame)
        self.pb_1_1.setGeometry(QtCore.QRect(40, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_1.setFont(font)
        self.pb_1_1.setStyleSheet("")
        self.pb_1_1.setObjectName("pb_1_1")
        self.pb_3_12 = QtWidgets.QPushButton(Frame)
        self.pb_3_12.setGeometry(QtCore.QRect(863, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_12.setFont(font)
        self.pb_3_12.setObjectName("pb_3_12")
        self.pb_2_1 = QtWidgets.QPushButton(Frame)
        self.pb_2_1.setGeometry(QtCore.QRect(44, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_1.setFont(font)
        self.pb_2_1.setObjectName("pb_2_1")
        self.pb_1_11 = QtWidgets.QPushButton(Frame)
        self.pb_1_11.setGeometry(QtCore.QRect(220, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_11.setFont(font)
        self.pb_1_11.setObjectName("pb_1_11")
        self.pb_4_16 = QtWidgets.QPushButton(Frame)
        self.pb_4_16.setGeometry(QtCore.QRect(939, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_16.setFont(font)
        self.pb_4_16.setObjectName("pb_4_16")
        self.pb_4_14 = QtWidgets.QPushButton(Frame)
        self.pb_4_14.setGeometry(QtCore.QRect(903, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_14.setFont(font)
        self.pb_4_14.setObjectName("pb_4_14")
        self.pb_4_30 = QtWidgets.QPushButton(Frame)
        self.pb_4_30.setGeometry(QtCore.QRect(1194, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_30.setFont(font)
        self.pb_4_30.setObjectName("pb_4_30")
        self.pb_2_11 = QtWidgets.QPushButton(Frame)
        self.pb_2_11.setGeometry(QtCore.QRect(222, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_11.setFont(font)
        self.pb_2_11.setObjectName("pb_2_11")
        self.pb_4_23 = QtWidgets.QPushButton(Frame)
        self.pb_4_23.setGeometry(QtCore.QRect(1066, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_23.setFont(font)
        self.pb_4_23.setObjectName("pb_4_23")
        self.pb_3_8 = QtWidgets.QPushButton(Frame)
        self.pb_3_8.setGeometry(QtCore.QRect(791, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_8.setFont(font)
        self.pb_3_8.setObjectName("pb_3_8")
        self.lbl_bar_code_1 = QtWidgets.QLabel(Frame)
        self.lbl_bar_code_1.setEnabled(True)
        self.lbl_bar_code_1.setGeometry(QtCore.QRect(188, 24, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_bar_code_1.setFont(font)
        self.lbl_bar_code_1.setObjectName("lbl_bar_code_1")
        self.pb_4_13 = QtWidgets.QPushButton(Frame)
        self.pb_4_13.setGeometry(QtCore.QRect(884, 488, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_13.setFont(font)
        self.pb_4_13.setObjectName("pb_4_13")
        self.pb_4_3 = QtWidgets.QPushButton(Frame)
        self.pb_4_3.setGeometry(QtCore.QRect(703, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_3.setFont(font)
        self.pb_4_3.setObjectName("pb_4_3")
        self.pb_2_19 = QtWidgets.QPushButton(Frame)
        self.pb_2_19.setGeometry(QtCore.QRect(364, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_19.setFont(font)
        self.pb_2_19.setObjectName("pb_2_19")
        self.pb_3_29 = QtWidgets.QPushButton(Frame)
        self.pb_3_29.setGeometry(QtCore.QRect(1172, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_29.setFont(font)
        self.pb_3_29.setObjectName("pb_3_29")
        self.pb_2_9 = QtWidgets.QPushButton(Frame)
        self.pb_2_9.setGeometry(QtCore.QRect(186, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_9.setFont(font)
        self.pb_2_9.setObjectName("pb_2_9")
        self.pb_4_19 = QtWidgets.QPushButton(Frame)
        self.pb_4_19.setGeometry(QtCore.QRect(993, 488, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_19.setFont(font)
        self.pb_4_19.setObjectName("pb_4_19")
        self.fSlot_3 = QtWidgets.QFrame(Frame)
        self.fSlot_3.setGeometry(QtCore.QRect(648, 74, 579, 141))
        self.fSlot_3.setAutoFillBackground(False)
        self.fSlot_3.setStyleSheet("")
        self.fSlot_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fSlot_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fSlot_3.setObjectName("fSlot_3")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.fSlot_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(12, 6, 553, 126))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gridLayoutWidget_4.setFont(font)
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.table_PN_test_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.table_PN_test_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.table_PN_test_3.setContentsMargins(0, 0, 0, 0)
        self.table_PN_test_3.setSpacing(1)
        self.table_PN_test_3.setObjectName("table_PN_test_3")
        self.lbl_lbl_measurement_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_lbl_measurement_3.setFont(font)
        self.lbl_lbl_measurement_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lbl_measurement_3.setObjectName("lbl_lbl_measurement_3")
        self.table_PN_test_3.addWidget(self.lbl_lbl_measurement_3, 0, 1, 1, 1)
        self.lbl_measurement_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_measurement_3.setFont(font)
        self.lbl_measurement_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_measurement_3.setObjectName("lbl_measurement_3")
        self.table_PN_test_3.addWidget(self.lbl_measurement_3, 1, 1, 1, 1)
        self.lbl_test_no_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_test_no_3.setFont(font)
        self.lbl_test_no_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_test_no_3.setObjectName("lbl_test_no_3")
        self.table_PN_test_3.addWidget(self.lbl_test_no_3, 1, 0, 1, 1)
        self.lbl_lbl_ResultTest_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_lbl_ResultTest_3.setFont(font)
        self.lbl_lbl_ResultTest_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lbl_ResultTest_3.setObjectName("lbl_lbl_ResultTest_3")
        self.table_PN_test_3.addWidget(self.lbl_lbl_ResultTest_3, 0, 2, 1, 1)
        self.lbl_ResultTest_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_ResultTest_3.setFont(font)
        self.lbl_ResultTest_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ResultTest_3.setObjectName("lbl_ResultTest_3")
        self.table_PN_test_3.addWidget(self.lbl_ResultTest_3, 1, 2, 1, 1)
        self.lbl_lbl_test_no_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_lbl_test_no_3.setFont(font)
        self.lbl_lbl_test_no_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lbl_test_no_3.setObjectName("lbl_lbl_test_no_3")
        self.table_PN_test_3.addWidget(self.lbl_lbl_test_no_3, 0, 0, 1, 1)
        self.pb_1_30 = QtWidgets.QPushButton(Frame)
        self.pb_1_30.setGeometry(QtCore.QRect(562, 216, 19, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_30.setFont(font)
        self.pb_1_30.setObjectName("pb_1_30")
        self.pb_4_5 = QtWidgets.QPushButton(Frame)
        self.pb_4_5.setGeometry(QtCore.QRect(739, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_5.setFont(font)
        self.pb_4_5.setObjectName("pb_4_5")
        self.pb_1_26 = QtWidgets.QPushButton(Frame)
        self.pb_1_26.setGeometry(QtCore.QRect(490, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_26.setFont(font)
        self.pb_1_26.setObjectName("pb_1_26")
        self.pb_1_23 = QtWidgets.QPushButton(Frame)
        self.pb_1_23.setGeometry(QtCore.QRect(436, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_23.setFont(font)
        self.pb_1_23.setObjectName("pb_1_23")
        self.pb_1_12 = QtWidgets.QPushButton(Frame)
        self.pb_1_12.setGeometry(QtCore.QRect(238, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_12.setFont(font)
        self.pb_1_12.setObjectName("pb_1_12")
        self.pb_2_3 = QtWidgets.QPushButton(Frame)
        self.pb_2_3.setGeometry(QtCore.QRect(80, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_3.setFont(font)
        self.pb_2_3.setObjectName("pb_2_3")
        self.pb_3_11 = QtWidgets.QPushButton(Frame)
        self.pb_3_11.setGeometry(QtCore.QRect(845, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_11.setFont(font)
        self.pb_3_11.setObjectName("pb_3_11")
        self.pb_1_9 = QtWidgets.QPushButton(Frame)
        self.pb_1_9.setGeometry(QtCore.QRect(184, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_9.setFont(font)
        self.pb_1_9.setObjectName("pb_1_9")
        self.pb_4_20 = QtWidgets.QPushButton(Frame)
        self.pb_4_20.setGeometry(QtCore.QRect(1012, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_20.setFont(font)
        self.pb_4_20.setObjectName("pb_4_20")
        self.pb_2_25 = QtWidgets.QPushButton(Frame)
        self.pb_2_25.setGeometry(QtCore.QRect(472, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_25.setFont(font)
        self.pb_2_25.setObjectName("pb_2_25")
        self.pb_2_6 = QtWidgets.QPushButton(Frame)
        self.pb_2_6.setGeometry(QtCore.QRect(133, 490, 19, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_6.setFont(font)
        self.pb_2_6.setObjectName("pb_2_6")
        self.lbl_bar_code_3 = QtWidgets.QLabel(Frame)
        self.lbl_bar_code_3.setEnabled(True)
        self.lbl_bar_code_3.setGeometry(QtCore.QRect(818, 24, 409, 61))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_bar_code_3.setFont(font)
        self.lbl_bar_code_3.setObjectName("lbl_bar_code_3")
        self.pb_2_15 = QtWidgets.QPushButton(Frame)
        self.pb_2_15.setGeometry(QtCore.QRect(293, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_15.setFont(font)
        self.pb_2_15.setObjectName("pb_2_15")
        self.pb_1_16 = QtWidgets.QPushButton(Frame)
        self.pb_1_16.setGeometry(QtCore.QRect(310, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_16.setFont(font)
        self.pb_1_16.setObjectName("pb_1_16")
        self.pb_4_17 = QtWidgets.QPushButton(Frame)
        self.pb_4_17.setGeometry(QtCore.QRect(957, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_17.setFont(font)
        self.pb_4_17.setObjectName("pb_4_17")
        self.pb_2_18 = QtWidgets.QPushButton(Frame)
        self.pb_2_18.setGeometry(QtCore.QRect(347, 490, 19, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_18.setFont(font)
        self.pb_2_18.setObjectName("pb_2_18")
        self.pb_3_26 = QtWidgets.QPushButton(Frame)
        self.pb_3_26.setGeometry(QtCore.QRect(1118, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_26.setFont(font)
        self.pb_3_26.setObjectName("pb_3_26")
        self.pb_1_3 = QtWidgets.QPushButton(Frame)
        self.pb_1_3.setGeometry(QtCore.QRect(76, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_3.setFont(font)
        self.pb_1_3.setObjectName("pb_1_3")
        self.pb_4_12 = QtWidgets.QPushButton(Frame)
        self.pb_4_12.setGeometry(QtCore.QRect(866, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_12.setFont(font)
        self.pb_4_12.setObjectName("pb_4_12")
        self.pb_1_5 = QtWidgets.QPushButton(Frame)
        self.pb_1_5.setGeometry(QtCore.QRect(112, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_5.setFont(font)
        self.pb_1_5.setObjectName("pb_1_5")
        self.pb_2_28 = QtWidgets.QPushButton(Frame)
        self.pb_2_28.setGeometry(QtCore.QRect(526, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_28.setFont(font)
        self.pb_2_28.setObjectName("pb_2_28")
        self.pb_3_9 = QtWidgets.QPushButton(Frame)
        self.pb_3_9.setGeometry(QtCore.QRect(809, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_9.setFont(font)
        self.pb_3_9.setObjectName("pb_3_9")
        self.pb_4_22 = QtWidgets.QPushButton(Frame)
        self.pb_4_22.setGeometry(QtCore.QRect(1048, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_22.setFont(font)
        self.pb_4_22.setObjectName("pb_4_22")
        self.pb_2_8 = QtWidgets.QPushButton(Frame)
        self.pb_2_8.setGeometry(QtCore.QRect(168, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_8.setFont(font)
        self.pb_2_8.setObjectName("pb_2_8")
        self.line_4 = QtWidgets.QFrame(Frame)
        self.line_4.setGeometry(QtCore.QRect(14, 2, 1217, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.pb_1_19 = QtWidgets.QPushButton(Frame)
        self.pb_1_19.setGeometry(QtCore.QRect(364, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_19.setFont(font)
        self.pb_1_19.setObjectName("pb_1_19")
        self.pb_3_27 = QtWidgets.QPushButton(Frame)
        self.pb_3_27.setGeometry(QtCore.QRect(1136, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_27.setFont(font)
        self.pb_3_27.setObjectName("pb_3_27")
        self.pb_3_4 = QtWidgets.QPushButton(Frame)
        self.pb_3_4.setGeometry(QtCore.QRect(718, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_4.setFont(font)
        self.pb_3_4.setObjectName("pb_3_4")
        self.pb_4_2 = QtWidgets.QPushButton(Frame)
        self.pb_4_2.setGeometry(QtCore.QRect(685, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_2.setFont(font)
        self.pb_4_2.setObjectName("pb_4_2")
        self.pb_1_18 = QtWidgets.QPushButton(Frame)
        self.pb_1_18.setGeometry(QtCore.QRect(346, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_18.setFont(font)
        self.pb_1_18.setObjectName("pb_1_18")
        self.pb_3_24 = QtWidgets.QPushButton(Frame)
        self.pb_3_24.setGeometry(QtCore.QRect(1082, 216, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_24.setFont(font)
        self.pb_3_24.setObjectName("pb_3_24")
        self.pb_3_20 = QtWidgets.QPushButton(Frame)
        self.pb_3_20.setGeometry(QtCore.QRect(1009, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_20.setFont(font)
        self.pb_3_20.setObjectName("pb_3_20")
        self.pb_1_28 = QtWidgets.QPushButton(Frame)
        self.pb_1_28.setGeometry(QtCore.QRect(526, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_28.setFont(font)
        self.pb_1_28.setObjectName("pb_1_28")
        self.pb_3_5 = QtWidgets.QPushButton(Frame)
        self.pb_3_5.setGeometry(QtCore.QRect(736, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_5.setFont(font)
        self.pb_3_5.setObjectName("pb_3_5")
        self.fSlot_2 = QtWidgets.QFrame(Frame)
        self.fSlot_2.setGeometry(QtCore.QRect(24, 340, 579, 141))
        self.fSlot_2.setAutoFillBackground(False)
        self.fSlot_2.setStyleSheet("")
        self.fSlot_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fSlot_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fSlot_2.setObjectName("fSlot_2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.fSlot_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(14, 6, 553, 126))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gridLayoutWidget_3.setFont(font)
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.table_PN_test_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.table_PN_test_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.table_PN_test_2.setContentsMargins(0, 0, 0, 0)
        self.table_PN_test_2.setSpacing(1)
        self.table_PN_test_2.setObjectName("table_PN_test_2")
        self.lbl_ResultTest_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_ResultTest_2.setFont(font)
        self.lbl_ResultTest_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ResultTest_2.setObjectName("lbl_ResultTest_2")
        self.table_PN_test_2.addWidget(self.lbl_ResultTest_2, 1, 2, 1, 1)
        self.lbl_lbl_test_no_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_lbl_test_no_2.setFont(font)
        self.lbl_lbl_test_no_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lbl_test_no_2.setObjectName("lbl_lbl_test_no_2")
        self.table_PN_test_2.addWidget(self.lbl_lbl_test_no_2, 0, 0, 1, 1)
        self.lbl_test_no_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_test_no_2.setFont(font)
        self.lbl_test_no_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_test_no_2.setObjectName("lbl_test_no_2")
        self.table_PN_test_2.addWidget(self.lbl_test_no_2, 1, 0, 1, 1)
        self.lbl_lbl_ResultTest_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_lbl_ResultTest_2.setFont(font)
        self.lbl_lbl_ResultTest_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lbl_ResultTest_2.setObjectName("lbl_lbl_ResultTest_2")
        self.table_PN_test_2.addWidget(self.lbl_lbl_ResultTest_2, 0, 2, 1, 1)
        self.lbl_lbl_measurement_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_lbl_measurement_2.setFont(font)
        self.lbl_lbl_measurement_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lbl_measurement_2.setObjectName("lbl_lbl_measurement_2")
        self.table_PN_test_2.addWidget(self.lbl_lbl_measurement_2, 0, 1, 1, 1)
        self.lbl_measurement_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_measurement_2.setFont(font)
        self.lbl_measurement_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_measurement_2.setObjectName("lbl_measurement_2")
        self.table_PN_test_2.addWidget(self.lbl_measurement_2, 1, 1, 1, 1)
        self.pb_1_10 = QtWidgets.QPushButton(Frame)
        self.pb_1_10.setGeometry(QtCore.QRect(202, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_10.setFont(font)
        self.pb_1_10.setObjectName("pb_1_10")
        self.pb_1_8 = QtWidgets.QPushButton(Frame)
        self.pb_1_8.setGeometry(QtCore.QRect(166, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_8.setFont(font)
        self.pb_1_8.setObjectName("pb_1_8")
        self.pb_2_26 = QtWidgets.QPushButton(Frame)
        self.pb_2_26.setGeometry(QtCore.QRect(490, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_26.setFont(font)
        self.pb_2_26.setObjectName("pb_2_26")
        self.pb_1_24 = QtWidgets.QPushButton(Frame)
        self.pb_1_24.setGeometry(QtCore.QRect(454, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_24.setFont(font)
        self.pb_1_24.setObjectName("pb_1_24")
        self.pb_1_13 = QtWidgets.QPushButton(Frame)
        self.pb_1_13.setGeometry(QtCore.QRect(256, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_13.setFont(font)
        self.pb_1_13.setObjectName("pb_1_13")
        self.fSlot_1 = QtWidgets.QFrame(Frame)
        self.fSlot_1.setGeometry(QtCore.QRect(22, 72, 579, 141))
        self.fSlot_1.setAutoFillBackground(False)
        self.fSlot_1.setStyleSheet("")
        self.fSlot_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fSlot_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fSlot_1.setObjectName("fSlot_1")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.fSlot_1)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(14, 8, 553, 126))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gridLayoutWidget_2.setFont(font)
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.table_PN_test = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.table_PN_test.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.table_PN_test.setContentsMargins(0, 0, 0, 0)
        self.table_PN_test.setSpacing(1)
        self.table_PN_test.setObjectName("table_PN_test")
        self.lbl_lbl_measurement_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_lbl_measurement_1.setFont(font)
        self.lbl_lbl_measurement_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lbl_measurement_1.setObjectName("lbl_lbl_measurement_1")
        self.table_PN_test.addWidget(self.lbl_lbl_measurement_1, 0, 1, 1, 1)
        self.lbl_ResultTest_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_ResultTest_1.setFont(font)
        self.lbl_ResultTest_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ResultTest_1.setObjectName("lbl_ResultTest_1")
        self.table_PN_test.addWidget(self.lbl_ResultTest_1, 1, 2, 1, 1)
        self.lbl_measurement_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_measurement_1.setFont(font)
        self.lbl_measurement_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_measurement_1.setObjectName("lbl_measurement_1")
        self.table_PN_test.addWidget(self.lbl_measurement_1, 1, 1, 1, 1)
        self.lbl_lbl_test_no_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_lbl_test_no_1.setFont(font)
        self.lbl_lbl_test_no_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lbl_test_no_1.setObjectName("lbl_lbl_test_no_1")
        self.table_PN_test.addWidget(self.lbl_lbl_test_no_1, 0, 0, 1, 1)
        self.lbl_lbl_ResultTest = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_lbl_ResultTest.setFont(font)
        self.lbl_lbl_ResultTest.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lbl_ResultTest.setObjectName("lbl_lbl_ResultTest")
        self.table_PN_test.addWidget(self.lbl_lbl_ResultTest, 0, 2, 1, 1)
        self.lbl_test_no_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_test_no_1.setFont(font)
        self.lbl_test_no_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_test_no_1.setObjectName("lbl_test_no_1")
        self.table_PN_test.addWidget(self.lbl_test_no_1, 1, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(Frame)
        self.line_3.setGeometry(QtCore.QRect(10, 538, 1223, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pb_2_27 = QtWidgets.QPushButton(Frame)
        self.pb_2_27.setGeometry(QtCore.QRect(508, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_27.setFont(font)
        self.pb_2_27.setObjectName("pb_2_27")
        self.lbl_lbl_product_2 = QtWidgets.QLabel(Frame)
        self.lbl_lbl_product_2.setGeometry(QtCore.QRect(42, 38, 29, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_lbl_product_2.setFont(font)
        self.lbl_lbl_product_2.setObjectName("lbl_lbl_product_2")
        self.pb_4_4 = QtWidgets.QPushButton(Frame)
        self.pb_4_4.setGeometry(QtCore.QRect(721, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_4.setFont(font)
        self.pb_4_4.setObjectName("pb_4_4")
        self.pb_2_24 = QtWidgets.QPushButton(Frame)
        self.pb_2_24.setGeometry(QtCore.QRect(455, 490, 19, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_24.setFont(font)
        self.pb_2_24.setObjectName("pb_2_24")
        self.pb_4_10 = QtWidgets.QPushButton(Frame)
        self.pb_4_10.setGeometry(QtCore.QRect(830, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_10.setFont(font)
        self.pb_4_10.setObjectName("pb_4_10")
        self.pb_4_1 = QtWidgets.QPushButton(Frame)
        self.pb_4_1.setGeometry(QtCore.QRect(667, 488, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_1.setFont(font)
        self.pb_4_1.setObjectName("pb_4_1")
        self.pb_1_29 = QtWidgets.QPushButton(Frame)
        self.pb_1_29.setGeometry(QtCore.QRect(544, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_29.setFont(font)
        self.pb_1_29.setObjectName("pb_1_29")
        self.pb_4_26 = QtWidgets.QPushButton(Frame)
        self.pb_4_26.setGeometry(QtCore.QRect(1122, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_26.setFont(font)
        self.pb_4_26.setObjectName("pb_4_26")
        self.pb_4_24 = QtWidgets.QPushButton(Frame)
        self.pb_4_24.setGeometry(QtCore.QRect(1084, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_24.setFont(font)
        self.pb_4_24.setObjectName("pb_4_24")
        self.pb_3_30 = QtWidgets.QPushButton(Frame)
        self.pb_3_30.setGeometry(QtCore.QRect(1190, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_30.setFont(font)
        self.pb_3_30.setObjectName("pb_3_30")
        self.fSlot_4 = QtWidgets.QFrame(Frame)
        self.fSlot_4.setGeometry(QtCore.QRect(648, 340, 579, 141))
        self.fSlot_4.setAutoFillBackground(False)
        self.fSlot_4.setStyleSheet("")
        self.fSlot_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fSlot_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fSlot_4.setObjectName("fSlot_4")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.fSlot_4)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(14, 8, 553, 126))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gridLayoutWidget_5.setFont(font)
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.table_PN_test_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.table_PN_test_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.table_PN_test_4.setContentsMargins(0, 0, 0, 0)
        self.table_PN_test_4.setSpacing(1)
        self.table_PN_test_4.setObjectName("table_PN_test_4")
        self.lbl_lbl_ResultTest_4 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_lbl_ResultTest_4.setFont(font)
        self.lbl_lbl_ResultTest_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lbl_ResultTest_4.setObjectName("lbl_lbl_ResultTest_4")
        self.table_PN_test_4.addWidget(self.lbl_lbl_ResultTest_4, 0, 2, 1, 1)
        self.lbl_measurement_4 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_measurement_4.setFont(font)
        self.lbl_measurement_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_measurement_4.setObjectName("lbl_measurement_4")
        self.table_PN_test_4.addWidget(self.lbl_measurement_4, 1, 1, 1, 1)
        self.lbl_test_no_4 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_test_no_4.setFont(font)
        self.lbl_test_no_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_test_no_4.setObjectName("lbl_test_no_4")
        self.table_PN_test_4.addWidget(self.lbl_test_no_4, 1, 0, 1, 1)
        self.lbl_lbl_measurement_4 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_lbl_measurement_4.setFont(font)
        self.lbl_lbl_measurement_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lbl_measurement_4.setObjectName("lbl_lbl_measurement_4")
        self.table_PN_test_4.addWidget(self.lbl_lbl_measurement_4, 0, 1, 1, 1)
        self.lbl_ResultTest_4 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_ResultTest_4.setFont(font)
        self.lbl_ResultTest_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ResultTest_4.setObjectName("lbl_ResultTest_4")
        self.table_PN_test_4.addWidget(self.lbl_ResultTest_4, 1, 2, 1, 1)
        self.lbl_lbl_test_no_4 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_lbl_test_no_4.setFont(font)
        self.lbl_lbl_test_no_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lbl_test_no_4.setObjectName("lbl_lbl_test_no_4")
        self.table_PN_test_4.addWidget(self.lbl_lbl_test_no_4, 0, 0, 1, 1)
        self.pb_1_21 = QtWidgets.QPushButton(Frame)
        self.pb_1_21.setGeometry(QtCore.QRect(400, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_21.setFont(font)
        self.pb_1_21.setObjectName("pb_1_21")
        self.lbl_bar_code_2 = QtWidgets.QLabel(Frame)
        self.lbl_bar_code_2.setEnabled(True)
        self.lbl_bar_code_2.setGeometry(QtCore.QRect(190, 290, 407, 61))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_bar_code_2.setFont(font)
        self.lbl_bar_code_2.setObjectName("lbl_bar_code_2")
        self.pb_4_25 = QtWidgets.QPushButton(Frame)
        self.pb_4_25.setGeometry(QtCore.QRect(1103, 488, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_25.setFont(font)
        self.pb_4_25.setObjectName("pb_4_25")
        self.pb_2_17 = QtWidgets.QPushButton(Frame)
        self.pb_2_17.setGeometry(QtCore.QRect(329, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_17.setFont(font)
        self.pb_2_17.setObjectName("pb_2_17")
        self.line_2 = QtWidgets.QFrame(Frame)
        self.line_2.setGeometry(QtCore.QRect(14, 268, 1215, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pb_4_6 = QtWidgets.QPushButton(Frame)
        self.pb_4_6.setGeometry(QtCore.QRect(757, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_6.setFont(font)
        self.pb_4_6.setObjectName("pb_4_6")
        self.lbl_lbl_product_5 = QtWidgets.QLabel(Frame)
        self.lbl_lbl_product_5.setGeometry(QtCore.QRect(666, 302, 29, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_lbl_product_5.setFont(font)
        self.lbl_lbl_product_5.setObjectName("lbl_lbl_product_5")
        self.pb_1_2 = QtWidgets.QPushButton(Frame)
        self.pb_1_2.setGeometry(QtCore.QRect(58, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_2.setFont(font)
        self.pb_1_2.setObjectName("pb_1_2")
        self.pb_3_23 = QtWidgets.QPushButton(Frame)
        self.pb_3_23.setGeometry(QtCore.QRect(1063, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_23.setFont(font)
        self.pb_3_23.setObjectName("pb_3_23")
        self.pb_3_22 = QtWidgets.QPushButton(Frame)
        self.pb_3_22.setGeometry(QtCore.QRect(1045, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_22.setFont(font)
        self.pb_3_22.setObjectName("pb_3_22")
        self.pb_1_4 = QtWidgets.QPushButton(Frame)
        self.pb_1_4.setGeometry(QtCore.QRect(94, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_4.setFont(font)
        self.pb_1_4.setObjectName("pb_1_4")
        self.lbl_lbl_product_4 = QtWidgets.QLabel(Frame)
        self.lbl_lbl_product_4.setGeometry(QtCore.QRect(662, 38, 29, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_lbl_product_4.setFont(font)
        self.lbl_lbl_product_4.setObjectName("lbl_lbl_product_4")
        self.pb_4_11 = QtWidgets.QPushButton(Frame)
        self.pb_4_11.setGeometry(QtCore.QRect(848, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_11.setFont(font)
        self.pb_4_11.setObjectName("pb_4_11")
        self.pb_2_14 = QtWidgets.QPushButton(Frame)
        self.pb_2_14.setGeometry(QtCore.QRect(275, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_14.setFont(font)
        self.pb_2_14.setObjectName("pb_2_14")
        self.pb_4_27 = QtWidgets.QPushButton(Frame)
        self.pb_4_27.setGeometry(QtCore.QRect(1140, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_27.setFont(font)
        self.pb_4_27.setObjectName("pb_4_27")
        self.pb_2_29 = QtWidgets.QPushButton(Frame)
        self.pb_2_29.setGeometry(QtCore.QRect(544, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_29.setFont(font)
        self.pb_2_29.setObjectName("pb_2_29")
        self.pb_3_10 = QtWidgets.QPushButton(Frame)
        self.pb_3_10.setGeometry(QtCore.QRect(827, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_10.setFont(font)
        self.pb_3_10.setObjectName("pb_3_10")
        self.pb_3_13 = QtWidgets.QPushButton(Frame)
        self.pb_3_13.setGeometry(QtCore.QRect(881, 216, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_13.setFont(font)
        self.pb_3_13.setObjectName("pb_3_13")
        self.pb_3_21 = QtWidgets.QPushButton(Frame)
        self.pb_3_21.setGeometry(QtCore.QRect(1027, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_21.setFont(font)
        self.pb_3_21.setObjectName("pb_3_21")
        self.pb_2_5 = QtWidgets.QPushButton(Frame)
        self.pb_2_5.setGeometry(QtCore.QRect(115, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_5.setFont(font)
        self.pb_2_5.setObjectName("pb_2_5")
        self.pb_2_22 = QtWidgets.QPushButton(Frame)
        self.pb_2_22.setGeometry(QtCore.QRect(418, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_22.setFont(font)
        self.pb_2_22.setObjectName("pb_2_22")
        self.pb_4_8 = QtWidgets.QPushButton(Frame)
        self.pb_4_8.setGeometry(QtCore.QRect(794, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_8.setFont(font)
        self.pb_4_8.setObjectName("pb_4_8")
        self.pb_2_16 = QtWidgets.QPushButton(Frame)
        self.pb_2_16.setGeometry(QtCore.QRect(311, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_16.setFont(font)
        self.pb_2_16.setObjectName("pb_2_16")
        self.pb_1_7 = QtWidgets.QPushButton(Frame)
        self.pb_1_7.setGeometry(QtCore.QRect(148, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_7.setFont(font)
        self.pb_1_7.setObjectName("pb_1_7")
        self.pb_2_7 = QtWidgets.QPushButton(Frame)
        self.pb_2_7.setGeometry(QtCore.QRect(150, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_7.setFont(font)
        self.pb_2_7.setObjectName("pb_2_7")
        self.pb_3_7 = QtWidgets.QPushButton(Frame)
        self.pb_3_7.setGeometry(QtCore.QRect(772, 216, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_7.setFont(font)
        self.pb_3_7.setObjectName("pb_3_7")
        self.pb_1_14 = QtWidgets.QPushButton(Frame)
        self.pb_1_14.setGeometry(QtCore.QRect(274, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_14.setFont(font)
        self.pb_1_14.setObjectName("pb_1_14")
        self.pb_2_30 = QtWidgets.QPushButton(Frame)
        self.pb_2_30.setGeometry(QtCore.QRect(562, 490, 19, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_30.setFont(font)
        self.pb_2_30.setObjectName("pb_2_30")
        self.pb_1_25 = QtWidgets.QPushButton(Frame)
        self.pb_1_25.setGeometry(QtCore.QRect(472, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_25.setFont(font)
        self.pb_1_25.setObjectName("pb_1_25")
        self.pb_3_2 = QtWidgets.QPushButton(Frame)
        self.pb_3_2.setGeometry(QtCore.QRect(682, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_2.setFont(font)
        self.pb_3_2.setObjectName("pb_3_2")
        self.pb_1_6 = QtWidgets.QPushButton(Frame)
        self.pb_1_6.setGeometry(QtCore.QRect(130, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_6.setFont(font)
        self.pb_1_6.setObjectName("pb_1_6")
        self.lbl_bar_code_4 = QtWidgets.QLabel(Frame)
        self.lbl_bar_code_4.setEnabled(True)
        self.lbl_bar_code_4.setGeometry(QtCore.QRect(816, 292, 407, 61))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_bar_code_4.setFont(font)
        self.lbl_bar_code_4.setObjectName("lbl_bar_code_4")
        self.pb_3_17 = QtWidgets.QPushButton(Frame)
        self.pb_3_17.setGeometry(QtCore.QRect(954, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_17.setFont(font)
        self.pb_3_17.setObjectName("pb_3_17")
        self.pb_3_16 = QtWidgets.QPushButton(Frame)
        self.pb_3_16.setGeometry(QtCore.QRect(936, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_16.setFont(font)
        self.pb_3_16.setObjectName("pb_3_16")
        self.pb_3_25 = QtWidgets.QPushButton(Frame)
        self.pb_3_25.setGeometry(QtCore.QRect(1100, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_25.setFont(font)
        self.pb_3_25.setObjectName("pb_3_25")
        self.pb_1_22 = QtWidgets.QPushButton(Frame)
        self.pb_1_22.setGeometry(QtCore.QRect(418, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_22.setFont(font)
        self.pb_1_22.setObjectName("pb_1_22")
        self.pb_2_20 = QtWidgets.QPushButton(Frame)
        self.pb_2_20.setGeometry(QtCore.QRect(382, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_20.setFont(font)
        self.pb_2_20.setObjectName("pb_2_20")
        self.pb_1_20 = QtWidgets.QPushButton(Frame)
        self.pb_1_20.setGeometry(QtCore.QRect(382, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_20.setFont(font)
        self.pb_1_20.setObjectName("pb_1_20")
        self.pb_1_27 = QtWidgets.QPushButton(Frame)
        self.pb_1_27.setGeometry(QtCore.QRect(508, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_27.setFont(font)
        self.pb_1_27.setObjectName("pb_1_27")
        self.pb_3_3 = QtWidgets.QPushButton(Frame)
        self.pb_3_3.setGeometry(QtCore.QRect(700, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_3.setFont(font)
        self.pb_3_3.setObjectName("pb_3_3")
        self.pb_4_9 = QtWidgets.QPushButton(Frame)
        self.pb_4_9.setGeometry(QtCore.QRect(812, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_9.setFont(font)
        self.pb_4_9.setObjectName("pb_4_9")
        self.pb_2_4 = QtWidgets.QPushButton(Frame)
        self.pb_2_4.setGeometry(QtCore.QRect(98, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_4.setFont(font)
        self.pb_2_4.setObjectName("pb_2_4")
        self.pb_3_28 = QtWidgets.QPushButton(Frame)
        self.pb_3_28.setGeometry(QtCore.QRect(1154, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_28.setFont(font)
        self.pb_3_28.setObjectName("pb_3_28")
        self.pb_3_19 = QtWidgets.QPushButton(Frame)
        self.pb_3_19.setGeometry(QtCore.QRect(990, 216, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_19.setFont(font)
        self.pb_3_19.setObjectName("pb_3_19")
        self.pb_2_13 = QtWidgets.QPushButton(Frame)
        self.pb_2_13.setGeometry(QtCore.QRect(257, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_13.setFont(font)
        self.pb_2_13.setObjectName("pb_2_13")
        self.lbl_lbl_product_3 = QtWidgets.QLabel(Frame)
        self.lbl_lbl_product_3.setGeometry(QtCore.QRect(48, 306, 29, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_lbl_product_3.setFont(font)
        self.lbl_lbl_product_3.setObjectName("lbl_lbl_product_3")
        self.pb_1_15 = QtWidgets.QPushButton(Frame)
        self.pb_1_15.setGeometry(QtCore.QRect(292, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_15.setFont(font)
        self.pb_1_15.setObjectName("pb_1_15")
        self.pb_4_7 = QtWidgets.QPushButton(Frame)
        self.pb_4_7.setGeometry(QtCore.QRect(775, 488, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_7.setFont(font)
        self.pb_4_7.setObjectName("pb_4_7")
        self.pb_2_12 = QtWidgets.QPushButton(Frame)
        self.pb_2_12.setGeometry(QtCore.QRect(240, 490, 19, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_12.setFont(font)
        self.pb_2_12.setObjectName("pb_2_12")
        self.pb_4_28 = QtWidgets.QPushButton(Frame)
        self.pb_4_28.setGeometry(QtCore.QRect(1158, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_28.setFont(font)
        self.pb_4_28.setObjectName("pb_4_28")
        self.pb_3_1 = QtWidgets.QPushButton(Frame)
        self.pb_3_1.setGeometry(QtCore.QRect(663, 216, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_1.setFont(font)
        self.pb_3_1.setObjectName("pb_3_1")
        self.pb_4_18 = QtWidgets.QPushButton(Frame)
        self.pb_4_18.setGeometry(QtCore.QRect(975, 488, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_18.setFont(font)
        self.pb_4_18.setObjectName("pb_4_18")
        self.pb_3_15 = QtWidgets.QPushButton(Frame)
        self.pb_3_15.setGeometry(QtCore.QRect(918, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_15.setFont(font)
        self.pb_3_15.setObjectName("pb_3_15")
        self.pb_2_23 = QtWidgets.QPushButton(Frame)
        self.pb_2_23.setGeometry(QtCore.QRect(437, 490, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_23.setFont(font)
        self.pb_2_23.setObjectName("pb_2_23")
        self.pb_1_17 = QtWidgets.QPushButton(Frame)
        self.pb_1_17.setGeometry(QtCore.QRect(328, 216, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_17.setFont(font)
        self.pb_1_17.setObjectName("pb_1_17")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.pb_3_14.setText(_translate("Frame", "14"))
        self.pb_4_21.setText(_translate("Frame", "21"))
        self.pb_4_29.setText(_translate("Frame", "29"))
        self.pb_3_18.setText(_translate("Frame", "18"))
        self.pb_4_15.setText(_translate("Frame", "15"))
        self.pb_2_2.setText(_translate("Frame", "2"))
        self.pb_2_21.setText(_translate("Frame", "21"))
        self.pb_3_6.setText(_translate("Frame", "6"))
        self.pb_2_10.setText(_translate("Frame", "10"))
        self.pb_1_1.setText(_translate("Frame", "1"))
        self.pb_3_12.setText(_translate("Frame", "12"))
        self.pb_2_1.setText(_translate("Frame", "1"))
        self.pb_1_11.setText(_translate("Frame", "11"))
        self.pb_4_16.setText(_translate("Frame", "16"))
        self.pb_4_14.setText(_translate("Frame", "14"))
        self.pb_4_30.setText(_translate("Frame", "30"))
        self.pb_2_11.setText(_translate("Frame", "11"))
        self.pb_4_23.setText(_translate("Frame", "23"))
        self.pb_3_8.setText(_translate("Frame", "8"))
        self.lbl_bar_code_1.setText(_translate("Frame", "000000000000000000"))
        self.pb_4_13.setText(_translate("Frame", "13"))
        self.pb_4_3.setText(_translate("Frame", "3"))
        self.pb_2_19.setText(_translate("Frame", "19"))
        self.pb_3_29.setText(_translate("Frame", "29"))
        self.pb_2_9.setText(_translate("Frame", "9"))
        self.pb_4_19.setText(_translate("Frame", "19"))
        self.lbl_lbl_measurement_3.setText(_translate("Frame", "Measurement"))
        self.lbl_measurement_3.setText(_translate("Frame", "?"))
        self.lbl_test_no_3.setText(_translate("Frame", "?"))
        self.lbl_lbl_ResultTest_3.setText(_translate("Frame", "Status"))
        self.lbl_ResultTest_3.setText(_translate("Frame", "?"))
        self.lbl_lbl_test_no_3.setText(_translate("Frame", "Last test"))
        self.pb_1_30.setText(_translate("Frame", "30"))
        self.pb_4_5.setText(_translate("Frame", "5"))
        self.pb_1_26.setText(_translate("Frame", "26"))
        self.pb_1_23.setText(_translate("Frame", "23"))
        self.pb_1_12.setText(_translate("Frame", "12"))
        self.pb_2_3.setText(_translate("Frame", "3"))
        self.pb_3_11.setText(_translate("Frame", "11"))
        self.pb_1_9.setText(_translate("Frame", "9"))
        self.pb_4_20.setText(_translate("Frame", "20"))
        self.pb_2_25.setText(_translate("Frame", "25"))
        self.pb_2_6.setText(_translate("Frame", "6"))
        self.lbl_bar_code_3.setText(_translate("Frame", "000000000000000000"))
        self.pb_2_15.setText(_translate("Frame", "15"))
        self.pb_1_16.setText(_translate("Frame", "16"))
        self.pb_4_17.setText(_translate("Frame", "17"))
        self.pb_2_18.setText(_translate("Frame", "18"))
        self.pb_3_26.setText(_translate("Frame", "26"))
        self.pb_1_3.setText(_translate("Frame", "3"))
        self.pb_4_12.setText(_translate("Frame", "12"))
        self.pb_1_5.setText(_translate("Frame", "5"))
        self.pb_2_28.setText(_translate("Frame", "28"))
        self.pb_3_9.setText(_translate("Frame", "9"))
        self.pb_4_22.setText(_translate("Frame", "22"))
        self.pb_2_8.setText(_translate("Frame", "8"))
        self.pb_1_19.setText(_translate("Frame", "19"))
        self.pb_3_27.setText(_translate("Frame", "27"))
        self.pb_3_4.setText(_translate("Frame", "4"))
        self.pb_4_2.setText(_translate("Frame", "2"))
        self.pb_1_18.setText(_translate("Frame", "18"))
        self.pb_3_24.setText(_translate("Frame", "24"))
        self.pb_3_20.setText(_translate("Frame", "20"))
        self.pb_1_28.setText(_translate("Frame", "28"))
        self.pb_3_5.setText(_translate("Frame", "5"))
        self.lbl_ResultTest_2.setText(_translate("Frame", "?"))
        self.lbl_lbl_test_no_2.setText(_translate("Frame", "Last test"))
        self.lbl_test_no_2.setText(_translate("Frame", "?"))
        self.lbl_lbl_ResultTest_2.setText(_translate("Frame", "Status"))
        self.lbl_lbl_measurement_2.setText(_translate("Frame", "Measurement"))
        self.lbl_measurement_2.setText(_translate("Frame", "?"))
        self.pb_1_10.setText(_translate("Frame", "10"))
        self.pb_1_8.setText(_translate("Frame", "8"))
        self.pb_2_26.setText(_translate("Frame", "26"))
        self.pb_1_24.setText(_translate("Frame", "24"))
        self.pb_1_13.setText(_translate("Frame", "13"))
        self.lbl_lbl_measurement_1.setText(_translate("Frame", "Measurement"))
        self.lbl_ResultTest_1.setText(_translate("Frame", "?"))
        self.lbl_measurement_1.setText(_translate("Frame", "?"))
        self.lbl_lbl_test_no_1.setText(_translate("Frame", "Last test"))
        self.lbl_lbl_ResultTest.setText(_translate("Frame", "Status"))
        self.lbl_test_no_1.setText(_translate("Frame", "?"))
        self.pb_2_27.setText(_translate("Frame", "27"))
        self.lbl_lbl_product_2.setText(_translate("Frame", "S1"))
        self.pb_4_4.setText(_translate("Frame", "4"))
        self.pb_2_24.setText(_translate("Frame", "24"))
        self.pb_4_10.setText(_translate("Frame", "10"))
        self.pb_4_1.setText(_translate("Frame", "1"))
        self.pb_1_29.setText(_translate("Frame", "29"))
        self.pb_4_26.setText(_translate("Frame", "26"))
        self.pb_4_24.setText(_translate("Frame", "24"))
        self.pb_3_30.setText(_translate("Frame", "30"))
        self.lbl_lbl_ResultTest_4.setText(_translate("Frame", "Status"))
        self.lbl_measurement_4.setText(_translate("Frame", "?"))
        self.lbl_test_no_4.setText(_translate("Frame", "?"))
        self.lbl_lbl_measurement_4.setText(_translate("Frame", "Measurement"))
        self.lbl_ResultTest_4.setText(_translate("Frame", "?"))
        self.lbl_lbl_test_no_4.setText(_translate("Frame", "Last test"))
        self.pb_1_21.setText(_translate("Frame", "21"))
        self.lbl_bar_code_2.setText(_translate("Frame", "000000000000000000"))
        self.pb_4_25.setText(_translate("Frame", "25"))
        self.pb_2_17.setText(_translate("Frame", "17"))
        self.pb_4_6.setText(_translate("Frame", "6"))
        self.lbl_lbl_product_5.setText(_translate("Frame", "S4"))
        self.pb_1_2.setText(_translate("Frame", "2"))
        self.pb_3_23.setText(_translate("Frame", "23"))
        self.pb_3_22.setText(_translate("Frame", "22"))
        self.pb_1_4.setText(_translate("Frame", "4"))
        self.lbl_lbl_product_4.setText(_translate("Frame", "S3"))
        self.pb_4_11.setText(_translate("Frame", "11"))
        self.pb_2_14.setText(_translate("Frame", "14"))
        self.pb_4_27.setText(_translate("Frame", "27"))
        self.pb_2_29.setText(_translate("Frame", "29"))
        self.pb_3_10.setText(_translate("Frame", "10"))
        self.pb_3_13.setText(_translate("Frame", "13"))
        self.pb_3_21.setText(_translate("Frame", "21"))
        self.pb_2_5.setText(_translate("Frame", "5"))
        self.pb_2_22.setText(_translate("Frame", "22"))
        self.pb_4_8.setText(_translate("Frame", "8"))
        self.pb_2_16.setText(_translate("Frame", "16"))
        self.pb_1_7.setText(_translate("Frame", "7"))
        self.pb_2_7.setText(_translate("Frame", "7"))
        self.pb_3_7.setText(_translate("Frame", "7"))
        self.pb_1_14.setText(_translate("Frame", "14"))
        self.pb_2_30.setText(_translate("Frame", "30"))
        self.pb_1_25.setText(_translate("Frame", "25"))
        self.pb_3_2.setText(_translate("Frame", "2"))
        self.pb_1_6.setText(_translate("Frame", "6"))
        self.lbl_bar_code_4.setText(_translate("Frame", "000000000000000000"))
        self.pb_3_17.setText(_translate("Frame", "17"))
        self.pb_3_16.setText(_translate("Frame", "16"))
        self.pb_3_25.setText(_translate("Frame", "25"))
        self.pb_1_22.setText(_translate("Frame", "22"))
        self.pb_2_20.setText(_translate("Frame", "20"))
        self.pb_1_20.setText(_translate("Frame", "20"))
        self.pb_1_27.setText(_translate("Frame", "27"))
        self.pb_3_3.setText(_translate("Frame", "3"))
        self.pb_4_9.setText(_translate("Frame", "9"))
        self.pb_2_4.setText(_translate("Frame", "4"))
        self.pb_3_28.setText(_translate("Frame", "28"))
        self.pb_3_19.setText(_translate("Frame", "19"))
        self.pb_2_13.setText(_translate("Frame", "13"))
        self.lbl_lbl_product_3.setText(_translate("Frame", "S2"))
        self.pb_1_15.setText(_translate("Frame", "15"))
        self.pb_4_7.setText(_translate("Frame", "7"))
        self.pb_2_12.setText(_translate("Frame", "12"))
        self.pb_4_28.setText(_translate("Frame", "28"))
        self.pb_3_1.setText(_translate("Frame", "1"))
        self.pb_4_18.setText(_translate("Frame", "18"))
        self.pb_3_15.setText(_translate("Frame", "15"))
        self.pb_2_23.setText(_translate("Frame", "23"))
        self.pb_1_17.setText(_translate("Frame", "17"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
