# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 't_rcm_14.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1280, 505)
        self.pb_1_28 = QtWidgets.QPushButton(Frame)
        self.pb_1_28.setGeometry(QtCore.QRect(1213, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_28.setFont(font)
        self.pb_1_28.setObjectName("pb_1_28")
        self.pb_3_5 = QtWidgets.QPushButton(Frame)
        self.pb_3_5.setGeometry(QtCore.QRect(799, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_5.setFont(font)
        self.pb_3_5.setObjectName("pb_3_5")
        self.pb_4_28 = QtWidgets.QPushButton(Frame)
        self.pb_4_28.setGeometry(QtCore.QRect(1217, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_28.setFont(font)
        self.pb_4_28.setObjectName("pb_4_28")
        self.pb_3_28 = QtWidgets.QPushButton(Frame)
        self.pb_3_28.setGeometry(QtCore.QRect(1217, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_28.setFont(font)
        self.pb_3_28.setObjectName("pb_3_28")
        self.pb_4_21 = QtWidgets.QPushButton(Frame)
        self.pb_4_21.setGeometry(QtCore.QRect(1089, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_21.setFont(font)
        self.pb_4_21.setObjectName("pb_4_21")
        self.line_10 = QtWidgets.QFrame(Frame)
        self.line_10.setGeometry(QtCore.QRect(707, 38, 16, 413))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.pb_2_10 = QtWidgets.QPushButton(Frame)
        self.pb_2_10.setGeometry(QtCore.QRect(887, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_10.setFont(font)
        self.pb_2_10.setObjectName("pb_2_10")
        self.pb_4_11 = QtWidgets.QPushButton(Frame)
        self.pb_4_11.setGeometry(QtCore.QRect(907, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_11.setFont(font)
        self.pb_4_11.setObjectName("pb_4_11")
        self.lbl_bar_code_4 = QtWidgets.QLabel(Frame)
        self.lbl_bar_code_4.setEnabled(True)
        self.lbl_bar_code_4.setGeometry(QtCore.QRect(73, 384, 295, 61))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_bar_code_4.setFont(font)
        self.lbl_bar_code_4.setObjectName("lbl_bar_code_4")
        self.pb_3_12 = QtWidgets.QPushButton(Frame)
        self.pb_3_12.setGeometry(QtCore.QRect(926, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_12.setFont(font)
        self.pb_3_12.setObjectName("pb_3_12")
        self.pb_4_18 = QtWidgets.QPushButton(Frame)
        self.pb_4_18.setGeometry(QtCore.QRect(1034, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_18.setFont(font)
        self.pb_4_18.setObjectName("pb_4_18")
        self.pb_3_14 = QtWidgets.QPushButton(Frame)
        self.pb_3_14.setGeometry(QtCore.QRect(963, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_14.setFont(font)
        self.pb_3_14.setObjectName("pb_3_14")
        self.pb_1_5 = QtWidgets.QPushButton(Frame)
        self.pb_1_5.setGeometry(QtCore.QRect(799, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_5.setFont(font)
        self.pb_1_5.setObjectName("pb_1_5")
        self.lbl_lbl_ResultTest_3 = QtWidgets.QLabel(Frame)
        self.lbl_lbl_ResultTest_3.setGeometry(QtCore.QRect(15, 52, 47, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_lbl_ResultTest_3.setFont(font)
        self.lbl_lbl_ResultTest_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lbl_ResultTest_3.setObjectName("lbl_lbl_ResultTest_3")
        self.pb_4_19 = QtWidgets.QPushButton(Frame)
        self.pb_4_19.setGeometry(QtCore.QRect(1052, 396, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_19.setFont(font)
        self.pb_4_19.setObjectName("pb_4_19")
        self.pb_2_29 = QtWidgets.QPushButton(Frame)
        self.pb_2_29.setGeometry(QtCore.QRect(1227, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_29.setFont(font)
        self.pb_2_29.setObjectName("pb_2_29")
        self.pb_2_12 = QtWidgets.QPushButton(Frame)
        self.pb_2_12.setGeometry(QtCore.QRect(923, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_12.setFont(font)
        self.pb_2_12.setObjectName("pb_2_12")
        self.line = QtWidgets.QFrame(Frame)
        self.line.setGeometry(QtCore.QRect(479, 38, 16, 415))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pb_1_3 = QtWidgets.QPushButton(Frame)
        self.pb_1_3.setGeometry(QtCore.QRect(763, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_3.setFont(font)
        self.pb_1_3.setObjectName("pb_1_3")
        self.pb_3_26 = QtWidgets.QPushButton(Frame)
        self.pb_3_26.setGeometry(QtCore.QRect(1181, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_26.setFont(font)
        self.pb_3_26.setObjectName("pb_3_26")
        self.pb_4_10 = QtWidgets.QPushButton(Frame)
        self.pb_4_10.setGeometry(QtCore.QRect(889, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_10.setFont(font)
        self.pb_4_10.setObjectName("pb_4_10")
        self.pb_1_7 = QtWidgets.QPushButton(Frame)
        self.pb_1_7.setGeometry(QtCore.QRect(835, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_7.setFont(font)
        self.pb_1_7.setObjectName("pb_1_7")
        self.pb_4_6 = QtWidgets.QPushButton(Frame)
        self.pb_4_6.setGeometry(QtCore.QRect(816, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_6.setFont(font)
        self.pb_4_6.setObjectName("pb_4_6")
        self.pb_4_22 = QtWidgets.QPushButton(Frame)
        self.pb_4_22.setGeometry(QtCore.QRect(1107, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_22.setFont(font)
        self.pb_4_22.setObjectName("pb_4_22")
        self.pb_3_20 = QtWidgets.QPushButton(Frame)
        self.pb_3_20.setGeometry(QtCore.QRect(1072, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_20.setFont(font)
        self.pb_3_20.setObjectName("pb_3_20")
        self.line_5 = QtWidgets.QFrame(Frame)
        self.line_5.setGeometry(QtCore.QRect(5, 274, 1280, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pb_3_30 = QtWidgets.QPushButton(Frame)
        self.pb_3_30.setGeometry(QtCore.QRect(1253, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_30.setFont(font)
        self.pb_3_30.setObjectName("pb_3_30")
        self.pb_3_4 = QtWidgets.QPushButton(Frame)
        self.pb_3_4.setGeometry(QtCore.QRect(781, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_4.setFont(font)
        self.pb_3_4.setObjectName("pb_3_4")
        self.pb_3_9 = QtWidgets.QPushButton(Frame)
        self.pb_3_9.setGeometry(QtCore.QRect(872, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_9.setFont(font)
        self.pb_3_9.setObjectName("pb_3_9")
        self.pb_2_7 = QtWidgets.QPushButton(Frame)
        self.pb_2_7.setGeometry(QtCore.QRect(833, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_7.setFont(font)
        self.pb_2_7.setObjectName("pb_2_7")
        self.pb_2_1 = QtWidgets.QPushButton(Frame)
        self.pb_2_1.setGeometry(QtCore.QRect(727, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_1.setFont(font)
        self.pb_2_1.setObjectName("pb_2_1")
        self.pb_4_12 = QtWidgets.QPushButton(Frame)
        self.pb_4_12.setGeometry(QtCore.QRect(925, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_12.setFont(font)
        self.pb_4_12.setObjectName("pb_4_12")
        self.pb_3_16 = QtWidgets.QPushButton(Frame)
        self.pb_3_16.setGeometry(QtCore.QRect(999, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_16.setFont(font)
        self.pb_3_16.setObjectName("pb_3_16")
        self.pb_2_13 = QtWidgets.QPushButton(Frame)
        self.pb_2_13.setGeometry(QtCore.QRect(940, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_13.setFont(font)
        self.pb_2_13.setObjectName("pb_2_13")
        self.pb_4_1 = QtWidgets.QPushButton(Frame)
        self.pb_4_1.setGeometry(QtCore.QRect(726, 396, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_1.setFont(font)
        self.pb_4_1.setObjectName("pb_4_1")
        self.pb_4_30 = QtWidgets.QPushButton(Frame)
        self.pb_4_30.setGeometry(QtCore.QRect(1253, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_30.setFont(font)
        self.pb_4_30.setObjectName("pb_4_30")
        self.pb_3_18 = QtWidgets.QPushButton(Frame)
        self.pb_3_18.setGeometry(QtCore.QRect(1035, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_18.setFont(font)
        self.pb_3_18.setObjectName("pb_3_18")
        self.pb_1_23 = QtWidgets.QPushButton(Frame)
        self.pb_1_23.setGeometry(QtCore.QRect(1123, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_23.setFont(font)
        self.pb_1_23.setObjectName("pb_1_23")
        self.pb_2_28 = QtWidgets.QPushButton(Frame)
        self.pb_2_28.setGeometry(QtCore.QRect(1209, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_28.setFont(font)
        self.pb_2_28.setObjectName("pb_2_28")
        self.pb_2_9 = QtWidgets.QPushButton(Frame)
        self.pb_2_9.setGeometry(QtCore.QRect(869, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_9.setFont(font)
        self.pb_2_9.setObjectName("pb_2_9")
        self.pb_4_2 = QtWidgets.QPushButton(Frame)
        self.pb_4_2.setGeometry(QtCore.QRect(744, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_2.setFont(font)
        self.pb_4_2.setObjectName("pb_4_2")
        self.pb_2_14 = QtWidgets.QPushButton(Frame)
        self.pb_2_14.setGeometry(QtCore.QRect(958, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_14.setFont(font)
        self.pb_2_14.setObjectName("pb_2_14")
        self.lbl_lbl_product_5 = QtWidgets.QLabel(Frame)
        self.lbl_lbl_product_5.setGeometry(QtCore.QRect(21, 398, 29, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_lbl_product_5.setFont(font)
        self.lbl_lbl_product_5.setObjectName("lbl_lbl_product_5")
        self.pb_1_29 = QtWidgets.QPushButton(Frame)
        self.pb_1_29.setGeometry(QtCore.QRect(1231, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_29.setFont(font)
        self.pb_1_29.setObjectName("pb_1_29")
        self.line_7 = QtWidgets.QFrame(Frame)
        self.line_7.setGeometry(QtCore.QRect(5, 32, 1280, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.lbl_lbl_product_3 = QtWidgets.QLabel(Frame)
        self.lbl_lbl_product_3.setGeometry(QtCore.QRect(17, 221, 29, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_lbl_product_3.setFont(font)
        self.lbl_lbl_product_3.setObjectName("lbl_lbl_product_3")
        self.pb_1_13 = QtWidgets.QPushButton(Frame)
        self.pb_1_13.setGeometry(QtCore.QRect(943, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_13.setFont(font)
        self.pb_1_13.setObjectName("pb_1_13")
        self.pb_1_19 = QtWidgets.QPushButton(Frame)
        self.pb_1_19.setGeometry(QtCore.QRect(1051, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_19.setFont(font)
        self.pb_1_19.setObjectName("pb_1_19")
        self.pb_2_16 = QtWidgets.QPushButton(Frame)
        self.pb_2_16.setGeometry(QtCore.QRect(994, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_16.setFont(font)
        self.pb_2_16.setObjectName("pb_2_16")
        self.pb_3_7 = QtWidgets.QPushButton(Frame)
        self.pb_3_7.setGeometry(QtCore.QRect(835, 306, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_7.setFont(font)
        self.pb_3_7.setObjectName("pb_3_7")
        self.pb_2_27 = QtWidgets.QPushButton(Frame)
        self.pb_2_27.setGeometry(QtCore.QRect(1191, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_27.setFont(font)
        self.pb_2_27.setObjectName("pb_2_27")
        self.pb_3_19 = QtWidgets.QPushButton(Frame)
        self.pb_3_19.setGeometry(QtCore.QRect(1053, 306, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_19.setFont(font)
        self.pb_3_19.setObjectName("pb_3_19")
        self.pb_2_24 = QtWidgets.QPushButton(Frame)
        self.pb_2_24.setGeometry(QtCore.QRect(1138, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_24.setFont(font)
        self.pb_2_24.setObjectName("pb_2_24")
        self.pb_2_15 = QtWidgets.QPushButton(Frame)
        self.pb_2_15.setGeometry(QtCore.QRect(976, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_15.setFont(font)
        self.pb_2_15.setObjectName("pb_2_15")
        self.pb_1_12 = QtWidgets.QPushButton(Frame)
        self.pb_1_12.setGeometry(QtCore.QRect(925, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_12.setFont(font)
        self.pb_1_12.setObjectName("pb_1_12")
        self.pb_1_1 = QtWidgets.QPushButton(Frame)
        self.pb_1_1.setGeometry(QtCore.QRect(727, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_1.setFont(font)
        self.pb_1_1.setStyleSheet("")
        self.pb_1_1.setObjectName("pb_1_1")
        self.pb_3_15 = QtWidgets.QPushButton(Frame)
        self.pb_3_15.setGeometry(QtCore.QRect(981, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_15.setFont(font)
        self.pb_3_15.setObjectName("pb_3_15")
        self.lbl_bar_code_2 = QtWidgets.QLabel(Frame)
        self.lbl_bar_code_2.setEnabled(True)
        self.lbl_bar_code_2.setGeometry(QtCore.QRect(71, 208, 289, 61))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_bar_code_2.setFont(font)
        self.lbl_bar_code_2.setObjectName("lbl_bar_code_2")
        self.pb_4_25 = QtWidgets.QPushButton(Frame)
        self.pb_4_25.setGeometry(QtCore.QRect(1162, 396, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_25.setFont(font)
        self.pb_4_25.setObjectName("pb_4_25")
        self.pb_3_13 = QtWidgets.QPushButton(Frame)
        self.pb_3_13.setGeometry(QtCore.QRect(944, 306, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_13.setFont(font)
        self.pb_3_13.setObjectName("pb_3_13")
        self.pb_3_22 = QtWidgets.QPushButton(Frame)
        self.pb_3_22.setGeometry(QtCore.QRect(1108, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_22.setFont(font)
        self.pb_3_22.setObjectName("pb_3_22")
        self.pb_1_22 = QtWidgets.QPushButton(Frame)
        self.pb_1_22.setGeometry(QtCore.QRect(1105, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_22.setFont(font)
        self.pb_1_22.setObjectName("pb_1_22")
        self.pb_2_23 = QtWidgets.QPushButton(Frame)
        self.pb_2_23.setGeometry(QtCore.QRect(1120, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_23.setFont(font)
        self.pb_2_23.setObjectName("pb_2_23")
        self.pb_4_20 = QtWidgets.QPushButton(Frame)
        self.pb_4_20.setGeometry(QtCore.QRect(1071, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_20.setFont(font)
        self.pb_4_20.setObjectName("pb_4_20")
        self.pb_2_20 = QtWidgets.QPushButton(Frame)
        self.pb_2_20.setGeometry(QtCore.QRect(1065, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_20.setFont(font)
        self.pb_2_20.setObjectName("pb_2_20")
        self.pb_2_4 = QtWidgets.QPushButton(Frame)
        self.pb_2_4.setGeometry(QtCore.QRect(781, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_4.setFont(font)
        self.pb_2_4.setObjectName("pb_2_4")
        self.pb_3_10 = QtWidgets.QPushButton(Frame)
        self.pb_3_10.setGeometry(QtCore.QRect(890, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_10.setFont(font)
        self.pb_3_10.setObjectName("pb_3_10")
        self.pb_4_13 = QtWidgets.QPushButton(Frame)
        self.pb_4_13.setGeometry(QtCore.QRect(943, 396, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_13.setFont(font)
        self.pb_4_13.setObjectName("pb_4_13")
        self.lbl_bar_code_1 = QtWidgets.QLabel(Frame)
        self.lbl_bar_code_1.setEnabled(True)
        self.lbl_bar_code_1.setGeometry(QtCore.QRect(71, 118, 295, 61))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_bar_code_1.setFont(font)
        self.lbl_bar_code_1.setObjectName("lbl_bar_code_1")
        self.pb_1_21 = QtWidgets.QPushButton(Frame)
        self.pb_1_21.setGeometry(QtCore.QRect(1087, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_21.setFont(font)
        self.pb_1_21.setObjectName("pb_1_21")
        self.pb_3_24 = QtWidgets.QPushButton(Frame)
        self.pb_3_24.setGeometry(QtCore.QRect(1145, 306, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_24.setFont(font)
        self.pb_3_24.setObjectName("pb_3_24")
        self.lbl_lbl_product_4 = QtWidgets.QLabel(Frame)
        self.lbl_lbl_product_4.setGeometry(QtCore.QRect(17, 306, 29, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_lbl_product_4.setFont(font)
        self.lbl_lbl_product_4.setObjectName("lbl_lbl_product_4")
        self.pb_4_17 = QtWidgets.QPushButton(Frame)
        self.pb_4_17.setGeometry(QtCore.QRect(1016, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_17.setFont(font)
        self.pb_4_17.setObjectName("pb_4_17")
        self.lbl_lbl_ResultTest_2 = QtWidgets.QLabel(Frame)
        self.lbl_lbl_ResultTest_2.setGeometry(QtCore.QRect(917, 52, 108, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_lbl_ResultTest_2.setFont(font)
        self.lbl_lbl_ResultTest_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lbl_ResultTest_2.setObjectName("lbl_lbl_ResultTest_2")
        self.pb_1_25 = QtWidgets.QPushButton(Frame)
        self.pb_1_25.setGeometry(QtCore.QRect(1159, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_25.setFont(font)
        self.pb_1_25.setObjectName("pb_1_25")
        self.line_11 = QtWidgets.QFrame(Frame)
        self.line_11.setGeometry(QtCore.QRect(59, 38, 16, 413))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.pb_4_8 = QtWidgets.QPushButton(Frame)
        self.pb_4_8.setGeometry(QtCore.QRect(853, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_8.setFont(font)
        self.pb_4_8.setObjectName("pb_4_8")
        self.pb_1_6 = QtWidgets.QPushButton(Frame)
        self.pb_1_6.setGeometry(QtCore.QRect(817, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_6.setFont(font)
        self.pb_1_6.setObjectName("pb_1_6")
        self.pb_3_11 = QtWidgets.QPushButton(Frame)
        self.pb_3_11.setGeometry(QtCore.QRect(908, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_11.setFont(font)
        self.pb_3_11.setObjectName("pb_3_11")
        self.pb_1_30 = QtWidgets.QPushButton(Frame)
        self.pb_1_30.setGeometry(QtCore.QRect(1249, 128, 19, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_30.setFont(font)
        self.pb_1_30.setObjectName("pb_1_30")
        self.pb_2_18 = QtWidgets.QPushButton(Frame)
        self.pb_2_18.setGeometry(QtCore.QRect(1030, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_18.setFont(font)
        self.pb_2_18.setObjectName("pb_2_18")
        self.pb_1_17 = QtWidgets.QPushButton(Frame)
        self.pb_1_17.setGeometry(QtCore.QRect(1015, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_17.setFont(font)
        self.pb_1_17.setObjectName("pb_1_17")
        self.pb_1_27 = QtWidgets.QPushButton(Frame)
        self.pb_1_27.setGeometry(QtCore.QRect(1195, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_27.setFont(font)
        self.pb_1_27.setObjectName("pb_1_27")
        self.pb_1_2 = QtWidgets.QPushButton(Frame)
        self.pb_1_2.setGeometry(QtCore.QRect(745, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_2.setFont(font)
        self.pb_1_2.setObjectName("pb_1_2")
        self.pb_1_26 = QtWidgets.QPushButton(Frame)
        self.pb_1_26.setGeometry(QtCore.QRect(1177, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_26.setFont(font)
        self.pb_1_26.setObjectName("pb_1_26")
        self.pb_2_5 = QtWidgets.QPushButton(Frame)
        self.pb_2_5.setGeometry(QtCore.QRect(798, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_5.setFont(font)
        self.pb_2_5.setObjectName("pb_2_5")
        self.line_2 = QtWidgets.QFrame(Frame)
        self.line_2.setGeometry(QtCore.QRect(5, 184, 1280, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pb_4_4 = QtWidgets.QPushButton(Frame)
        self.pb_4_4.setGeometry(QtCore.QRect(780, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_4.setFont(font)
        self.pb_4_4.setObjectName("pb_4_4")
        self.pb_3_8 = QtWidgets.QPushButton(Frame)
        self.pb_3_8.setGeometry(QtCore.QRect(854, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_8.setFont(font)
        self.pb_3_8.setObjectName("pb_3_8")
        self.pb_3_17 = QtWidgets.QPushButton(Frame)
        self.pb_3_17.setGeometry(QtCore.QRect(1017, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_17.setFont(font)
        self.pb_3_17.setObjectName("pb_3_17")
        self.pb_2_19 = QtWidgets.QPushButton(Frame)
        self.pb_2_19.setGeometry(QtCore.QRect(1047, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_19.setFont(font)
        self.pb_2_19.setObjectName("pb_2_19")
        self.pb_3_29 = QtWidgets.QPushButton(Frame)
        self.pb_3_29.setGeometry(QtCore.QRect(1235, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_29.setFont(font)
        self.pb_3_29.setObjectName("pb_3_29")
        self.line_6 = QtWidgets.QFrame(Frame)
        self.line_6.setGeometry(QtCore.QRect(3, 362, 1283, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.pb_3_27 = QtWidgets.QPushButton(Frame)
        self.pb_3_27.setGeometry(QtCore.QRect(1199, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_27.setFont(font)
        self.pb_3_27.setObjectName("pb_3_27")
        self.pb_1_10 = QtWidgets.QPushButton(Frame)
        self.pb_1_10.setGeometry(QtCore.QRect(889, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_10.setFont(font)
        self.pb_1_10.setObjectName("pb_1_10")
        self.pb_4_24 = QtWidgets.QPushButton(Frame)
        self.pb_4_24.setGeometry(QtCore.QRect(1143, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_24.setFont(font)
        self.pb_4_24.setObjectName("pb_4_24")
        self.pb_1_16 = QtWidgets.QPushButton(Frame)
        self.pb_1_16.setGeometry(QtCore.QRect(997, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_16.setFont(font)
        self.pb_1_16.setObjectName("pb_1_16")
        self.pb_3_25 = QtWidgets.QPushButton(Frame)
        self.pb_3_25.setGeometry(QtCore.QRect(1163, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_25.setFont(font)
        self.pb_3_25.setObjectName("pb_3_25")
        self.pb_3_21 = QtWidgets.QPushButton(Frame)
        self.pb_3_21.setGeometry(QtCore.QRect(1090, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_21.setFont(font)
        self.pb_3_21.setObjectName("pb_3_21")
        self.pb_2_2 = QtWidgets.QPushButton(Frame)
        self.pb_2_2.setGeometry(QtCore.QRect(745, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_2.setFont(font)
        self.pb_2_2.setObjectName("pb_2_2")
        self.pb_2_30 = QtWidgets.QPushButton(Frame)
        self.pb_2_30.setGeometry(QtCore.QRect(1245, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_30.setFont(font)
        self.pb_2_30.setObjectName("pb_2_30")
        self.pb_2_25 = QtWidgets.QPushButton(Frame)
        self.pb_2_25.setGeometry(QtCore.QRect(1155, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_25.setFont(font)
        self.pb_2_25.setObjectName("pb_2_25")
        self.pb_2_11 = QtWidgets.QPushButton(Frame)
        self.pb_2_11.setGeometry(QtCore.QRect(905, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_11.setFont(font)
        self.pb_2_11.setObjectName("pb_2_11")
        self.pb_1_9 = QtWidgets.QPushButton(Frame)
        self.pb_1_9.setGeometry(QtCore.QRect(871, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_9.setFont(font)
        self.pb_1_9.setObjectName("pb_1_9")
        self.pb_2_22 = QtWidgets.QPushButton(Frame)
        self.pb_2_22.setGeometry(QtCore.QRect(1101, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_22.setFont(font)
        self.pb_2_22.setObjectName("pb_2_22")
        self.pb_1_15 = QtWidgets.QPushButton(Frame)
        self.pb_1_15.setGeometry(QtCore.QRect(979, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_15.setFont(font)
        self.pb_1_15.setObjectName("pb_1_15")
        self.pb_3_23 = QtWidgets.QPushButton(Frame)
        self.pb_3_23.setGeometry(QtCore.QRect(1126, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_23.setFont(font)
        self.pb_3_23.setObjectName("pb_3_23")
        self.lbl_lbl_product_2 = QtWidgets.QLabel(Frame)
        self.lbl_lbl_product_2.setGeometry(QtCore.QRect(17, 132, 29, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_lbl_product_2.setFont(font)
        self.lbl_lbl_product_2.setObjectName("lbl_lbl_product_2")
        self.pb_4_7 = QtWidgets.QPushButton(Frame)
        self.pb_4_7.setGeometry(QtCore.QRect(834, 396, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_7.setFont(font)
        self.pb_4_7.setObjectName("pb_4_7")
        self.lbl_lbl_ResultTest_4 = QtWidgets.QLabel(Frame)
        self.lbl_lbl_ResultTest_4.setGeometry(QtCore.QRect(149, 52, 115, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_lbl_ResultTest_4.setFont(font)
        self.lbl_lbl_ResultTest_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lbl_ResultTest_4.setObjectName("lbl_lbl_ResultTest_4")
        self.pb_2_26 = QtWidgets.QPushButton(Frame)
        self.pb_2_26.setGeometry(QtCore.QRect(1173, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_26.setFont(font)
        self.pb_2_26.setObjectName("pb_2_26")
        self.pb_4_3 = QtWidgets.QPushButton(Frame)
        self.pb_4_3.setGeometry(QtCore.QRect(762, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_3.setFont(font)
        self.pb_4_3.setObjectName("pb_4_3")
        self.pb_4_5 = QtWidgets.QPushButton(Frame)
        self.pb_4_5.setGeometry(QtCore.QRect(798, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_5.setFont(font)
        self.pb_4_5.setObjectName("pb_4_5")
        self.pb_4_23 = QtWidgets.QPushButton(Frame)
        self.pb_4_23.setGeometry(QtCore.QRect(1125, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_23.setFont(font)
        self.pb_4_23.setObjectName("pb_4_23")
        self.pb_4_9 = QtWidgets.QPushButton(Frame)
        self.pb_4_9.setGeometry(QtCore.QRect(871, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_9.setFont(font)
        self.pb_4_9.setObjectName("pb_4_9")
        self.pb_2_17 = QtWidgets.QPushButton(Frame)
        self.pb_2_17.setGeometry(QtCore.QRect(1012, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_17.setFont(font)
        self.pb_2_17.setObjectName("pb_2_17")
        self.pb_1_14 = QtWidgets.QPushButton(Frame)
        self.pb_1_14.setGeometry(QtCore.QRect(961, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_14.setFont(font)
        self.pb_1_14.setObjectName("pb_1_14")
        self.pb_1_4 = QtWidgets.QPushButton(Frame)
        self.pb_1_4.setGeometry(QtCore.QRect(781, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_4.setFont(font)
        self.pb_1_4.setObjectName("pb_1_4")
        self.pb_3_3 = QtWidgets.QPushButton(Frame)
        self.pb_3_3.setGeometry(QtCore.QRect(763, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_3.setFont(font)
        self.pb_3_3.setObjectName("pb_3_3")
        self.pb_2_8 = QtWidgets.QPushButton(Frame)
        self.pb_2_8.setGeometry(QtCore.QRect(851, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_8.setFont(font)
        self.pb_2_8.setObjectName("pb_2_8")
        self.pb_2_21 = QtWidgets.QPushButton(Frame)
        self.pb_2_21.setGeometry(QtCore.QRect(1083, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_21.setFont(font)
        self.pb_2_21.setObjectName("pb_2_21")
        self.pb_4_26 = QtWidgets.QPushButton(Frame)
        self.pb_4_26.setGeometry(QtCore.QRect(1181, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_26.setFont(font)
        self.pb_4_26.setObjectName("pb_4_26")
        self.line_9 = QtWidgets.QFrame(Frame)
        self.line_9.setGeometry(QtCore.QRect(367, 38, 16, 413))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.pb_1_18 = QtWidgets.QPushButton(Frame)
        self.pb_1_18.setGeometry(QtCore.QRect(1033, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_18.setFont(font)
        self.pb_1_18.setObjectName("pb_1_18")
        self.pb_4_16 = QtWidgets.QPushButton(Frame)
        self.pb_4_16.setGeometry(QtCore.QRect(998, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_16.setFont(font)
        self.pb_4_16.setObjectName("pb_4_16")
        self.pb_1_24 = QtWidgets.QPushButton(Frame)
        self.pb_1_24.setGeometry(QtCore.QRect(1141, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_24.setFont(font)
        self.pb_1_24.setObjectName("pb_1_24")
        self.line_8 = QtWidgets.QFrame(Frame)
        self.line_8.setGeometry(QtCore.QRect(589, 40, 16, 409))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_4 = QtWidgets.QFrame(Frame)
        self.line_4.setGeometry(QtCore.QRect(3, 96, 1280, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.lbl_bar_code_3 = QtWidgets.QLabel(Frame)
        self.lbl_bar_code_3.setEnabled(True)
        self.lbl_bar_code_3.setGeometry(QtCore.QRect(73, 292, 297, 61))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_bar_code_3.setFont(font)
        self.lbl_bar_code_3.setObjectName("lbl_bar_code_3")
        self.pb_1_11 = QtWidgets.QPushButton(Frame)
        self.pb_1_11.setGeometry(QtCore.QRect(907, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_11.setFont(font)
        self.pb_1_11.setObjectName("pb_1_11")
        self.pb_3_6 = QtWidgets.QPushButton(Frame)
        self.pb_3_6.setGeometry(QtCore.QRect(817, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_6.setFont(font)
        self.pb_3_6.setObjectName("pb_3_6")
        self.pb_1_8 = QtWidgets.QPushButton(Frame)
        self.pb_1_8.setGeometry(QtCore.QRect(853, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_8.setFont(font)
        self.pb_1_8.setObjectName("pb_1_8")
        self.pb_4_15 = QtWidgets.QPushButton(Frame)
        self.pb_4_15.setGeometry(QtCore.QRect(980, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_15.setFont(font)
        self.pb_4_15.setObjectName("pb_4_15")
        self.pb_4_27 = QtWidgets.QPushButton(Frame)
        self.pb_4_27.setGeometry(QtCore.QRect(1199, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_27.setFont(font)
        self.pb_4_27.setObjectName("pb_4_27")
        self.gridLayoutWidget = QtWidgets.QWidget(Frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(375, 40, 341, 393))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_test_no_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_test_no_2.setFont(font)
        self.lbl_test_no_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_test_no_2.setObjectName("lbl_test_no_2")
        self.horizontalLayout_3.addWidget(self.lbl_test_no_2)
        self.lbl_measurement_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_measurement_2.setFont(font)
        self.lbl_measurement_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_measurement_2.setWordWrap(True)
        self.lbl_measurement_2.setObjectName("lbl_measurement_2")
        self.horizontalLayout_3.addWidget(self.lbl_measurement_2)
        self.lbl_ResultTest_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_ResultTest_2.setFont(font)
        self.lbl_ResultTest_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ResultTest_2.setObjectName("lbl_ResultTest_2")
        self.horizontalLayout_3.addWidget(self.lbl_ResultTest_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_test_no_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_test_no_1.setFont(font)
        self.lbl_test_no_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_test_no_1.setObjectName("lbl_test_no_1")
        self.horizontalLayout_2.addWidget(self.lbl_test_no_1)
        self.lbl_measurement_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_measurement_1.setFont(font)
        self.lbl_measurement_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_measurement_1.setWordWrap(True)
        self.lbl_measurement_1.setObjectName("lbl_measurement_1")
        self.horizontalLayout_2.addWidget(self.lbl_measurement_1)
        self.lbl_ResultTest_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_ResultTest_1.setFont(font)
        self.lbl_ResultTest_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ResultTest_1.setObjectName("lbl_ResultTest_1")
        self.horizontalLayout_2.addWidget(self.lbl_ResultTest_1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_lbl_test_no_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_lbl_test_no_1.setFont(font)
        self.lbl_lbl_test_no_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lbl_test_no_1.setObjectName("lbl_lbl_test_no_1")
        self.horizontalLayout_6.addWidget(self.lbl_lbl_test_no_1)
        self.lbl_lbl_measurement_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_lbl_measurement_1.setFont(font)
        self.lbl_lbl_measurement_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lbl_measurement_1.setObjectName("lbl_lbl_measurement_1")
        self.horizontalLayout_6.addWidget(self.lbl_lbl_measurement_1)
        self.lbl_lbl_ResultTest = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_lbl_ResultTest.setFont(font)
        self.lbl_lbl_ResultTest.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lbl_ResultTest.setObjectName("lbl_lbl_ResultTest")
        self.horizontalLayout_6.addWidget(self.lbl_lbl_ResultTest)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_test_no_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_test_no_4.setFont(font)
        self.lbl_test_no_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_test_no_4.setObjectName("lbl_test_no_4")
        self.horizontalLayout_5.addWidget(self.lbl_test_no_4)
        self.lbl_measurement_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_measurement_4.setFont(font)
        self.lbl_measurement_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_measurement_4.setWordWrap(True)
        self.lbl_measurement_4.setObjectName("lbl_measurement_4")
        self.horizontalLayout_5.addWidget(self.lbl_measurement_4)
        self.lbl_ResultTest_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_ResultTest_4.setFont(font)
        self.lbl_ResultTest_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ResultTest_4.setObjectName("lbl_ResultTest_4")
        self.horizontalLayout_5.addWidget(self.lbl_ResultTest_4)
        self.gridLayout.addLayout(self.horizontalLayout_5, 9, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_test_no_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_test_no_3.setFont(font)
        self.lbl_test_no_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_test_no_3.setObjectName("lbl_test_no_3")
        self.horizontalLayout_4.addWidget(self.lbl_test_no_3)
        self.lbl_measurement_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_measurement_3.setFont(font)
        self.lbl_measurement_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_measurement_3.setWordWrap(True)
        self.lbl_measurement_3.setObjectName("lbl_measurement_3")
        self.horizontalLayout_4.addWidget(self.lbl_measurement_3)
        self.lbl_ResultTest_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_ResultTest_3.setFont(font)
        self.lbl_ResultTest_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ResultTest_3.setObjectName("lbl_ResultTest_3")
        self.horizontalLayout_4.addWidget(self.lbl_ResultTest_3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 7, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 6, 0, 1, 1)
        self.pb_2_6 = QtWidgets.QPushButton(Frame)
        self.pb_2_6.setGeometry(QtCore.QRect(816, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_6.setFont(font)
        self.pb_2_6.setObjectName("pb_2_6")
        self.line_3 = QtWidgets.QFrame(Frame)
        self.line_3.setGeometry(QtCore.QRect(5, 444, 1275, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pb_4_14 = QtWidgets.QPushButton(Frame)
        self.pb_4_14.setGeometry(QtCore.QRect(962, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_14.setFont(font)
        self.pb_4_14.setObjectName("pb_4_14")
        self.pb_3_2 = QtWidgets.QPushButton(Frame)
        self.pb_3_2.setGeometry(QtCore.QRect(745, 306, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_2.setFont(font)
        self.pb_3_2.setObjectName("pb_3_2")
        self.pb_2_3 = QtWidgets.QPushButton(Frame)
        self.pb_2_3.setGeometry(QtCore.QRect(763, 220, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_2_3.setFont(font)
        self.pb_2_3.setObjectName("pb_2_3")
        self.pb_4_29 = QtWidgets.QPushButton(Frame)
        self.pb_4_29.setGeometry(QtCore.QRect(1235, 396, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_4_29.setFont(font)
        self.pb_4_29.setObjectName("pb_4_29")
        self.pb_1_20 = QtWidgets.QPushButton(Frame)
        self.pb_1_20.setGeometry(QtCore.QRect(1069, 128, 20, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_1_20.setFont(font)
        self.pb_1_20.setObjectName("pb_1_20")
        self.pb_3_1 = QtWidgets.QPushButton(Frame)
        self.pb_3_1.setGeometry(QtCore.QRect(726, 306, 21, 35))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pb_3_1.setFont(font)
        self.pb_3_1.setObjectName("pb_3_1")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.pb_1_28.setText(_translate("Frame", "28"))
        self.pb_3_5.setText(_translate("Frame", "5"))
        self.pb_4_28.setText(_translate("Frame", "28"))
        self.pb_3_28.setText(_translate("Frame", "28"))
        self.pb_4_21.setText(_translate("Frame", "21"))
        self.pb_2_10.setText(_translate("Frame", "10"))
        self.pb_4_11.setText(_translate("Frame", "11"))
        self.lbl_bar_code_4.setText(_translate("Frame", "000000000000000000"))
        self.pb_3_12.setText(_translate("Frame", "12"))
        self.pb_4_18.setText(_translate("Frame", "18"))
        self.pb_3_14.setText(_translate("Frame", "14"))
        self.pb_1_5.setText(_translate("Frame", "5"))
        self.lbl_lbl_ResultTest_3.setText(_translate("Frame", "SLOT"))
        self.pb_4_19.setText(_translate("Frame", "19"))
        self.pb_2_29.setText(_translate("Frame", "29"))
        self.pb_2_12.setText(_translate("Frame", "12"))
        self.pb_1_3.setText(_translate("Frame", "3"))
        self.pb_3_26.setText(_translate("Frame", "26"))
        self.pb_4_10.setText(_translate("Frame", "10"))
        self.pb_1_7.setText(_translate("Frame", "7"))
        self.pb_4_6.setText(_translate("Frame", "6"))
        self.pb_4_22.setText(_translate("Frame", "22"))
        self.pb_3_20.setText(_translate("Frame", "20"))
        self.pb_3_30.setText(_translate("Frame", "30"))
        self.pb_3_4.setText(_translate("Frame", "4"))
        self.pb_3_9.setText(_translate("Frame", "9"))
        self.pb_2_7.setText(_translate("Frame", "7"))
        self.pb_2_1.setText(_translate("Frame", "1"))
        self.pb_4_12.setText(_translate("Frame", "12"))
        self.pb_3_16.setText(_translate("Frame", "16"))
        self.pb_2_13.setText(_translate("Frame", "13"))
        self.pb_4_1.setText(_translate("Frame", "1"))
        self.pb_4_30.setText(_translate("Frame", "30"))
        self.pb_3_18.setText(_translate("Frame", "18"))
        self.pb_1_23.setText(_translate("Frame", "23"))
        self.pb_2_28.setText(_translate("Frame", "28"))
        self.pb_2_9.setText(_translate("Frame", "9"))
        self.pb_4_2.setText(_translate("Frame", "2"))
        self.pb_2_14.setText(_translate("Frame", "14"))
        self.lbl_lbl_product_5.setText(_translate("Frame", "S4"))
        self.pb_1_29.setText(_translate("Frame", "29"))
        self.lbl_lbl_product_3.setText(_translate("Frame", "S2"))
        self.pb_1_13.setText(_translate("Frame", "13"))
        self.pb_1_19.setText(_translate("Frame", "19"))
        self.pb_2_16.setText(_translate("Frame", "16"))
        self.pb_3_7.setText(_translate("Frame", "7"))
        self.pb_2_27.setText(_translate("Frame", "27"))
        self.pb_3_19.setText(_translate("Frame", "19"))
        self.pb_2_24.setText(_translate("Frame", "24"))
        self.pb_2_15.setText(_translate("Frame", "15"))
        self.pb_1_12.setText(_translate("Frame", "12"))
        self.pb_1_1.setText(_translate("Frame", "1"))
        self.pb_3_15.setText(_translate("Frame", "15"))
        self.lbl_bar_code_2.setText(_translate("Frame", "000000000000000000"))
        self.pb_4_25.setText(_translate("Frame", "25"))
        self.pb_3_13.setText(_translate("Frame", "13"))
        self.pb_3_22.setText(_translate("Frame", "22"))
        self.pb_1_22.setText(_translate("Frame", "22"))
        self.pb_2_23.setText(_translate("Frame", "23"))
        self.pb_4_20.setText(_translate("Frame", "20"))
        self.pb_2_20.setText(_translate("Frame", "20"))
        self.pb_2_4.setText(_translate("Frame", "4"))
        self.pb_3_10.setText(_translate("Frame", "10"))
        self.pb_4_13.setText(_translate("Frame", "13"))
        self.lbl_bar_code_1.setText(_translate("Frame", "000000000000000000"))
        self.pb_1_21.setText(_translate("Frame", "21"))
        self.pb_3_24.setText(_translate("Frame", "24"))
        self.lbl_lbl_product_4.setText(_translate("Frame", "S3"))
        self.pb_4_17.setText(_translate("Frame", "17"))
        self.lbl_lbl_ResultTest_2.setText(_translate("Frame", "Test results"))
        self.pb_1_25.setText(_translate("Frame", "25"))
        self.pb_4_8.setText(_translate("Frame", "8"))
        self.pb_1_6.setText(_translate("Frame", "6"))
        self.pb_3_11.setText(_translate("Frame", "11"))
        self.pb_1_30.setText(_translate("Frame", "30"))
        self.pb_2_18.setText(_translate("Frame", "18"))
        self.pb_1_17.setText(_translate("Frame", "17"))
        self.pb_1_27.setText(_translate("Frame", "27"))
        self.pb_1_2.setText(_translate("Frame", "2"))
        self.pb_1_26.setText(_translate("Frame", "26"))
        self.pb_2_5.setText(_translate("Frame", "5"))
        self.pb_4_4.setText(_translate("Frame", "4"))
        self.pb_3_8.setText(_translate("Frame", "8"))
        self.pb_3_17.setText(_translate("Frame", "17"))
        self.pb_2_19.setText(_translate("Frame", "19"))
        self.pb_3_29.setText(_translate("Frame", "29"))
        self.pb_3_27.setText(_translate("Frame", "27"))
        self.pb_1_10.setText(_translate("Frame", "10"))
        self.pb_4_24.setText(_translate("Frame", "24"))
        self.pb_1_16.setText(_translate("Frame", "16"))
        self.pb_3_25.setText(_translate("Frame", "25"))
        self.pb_3_21.setText(_translate("Frame", "21"))
        self.pb_2_2.setText(_translate("Frame", "2"))
        self.pb_2_30.setText(_translate("Frame", "30"))
        self.pb_2_25.setText(_translate("Frame", "25"))
        self.pb_2_11.setText(_translate("Frame", "11"))
        self.pb_1_9.setText(_translate("Frame", "9"))
        self.pb_2_22.setText(_translate("Frame", "22"))
        self.pb_1_15.setText(_translate("Frame", "15"))
        self.pb_3_23.setText(_translate("Frame", "23"))
        self.lbl_lbl_product_2.setText(_translate("Frame", "S1"))
        self.pb_4_7.setText(_translate("Frame", "7"))
        self.lbl_lbl_ResultTest_4.setText(_translate("Frame", "BAR CODE"))
        self.pb_2_26.setText(_translate("Frame", "26"))
        self.pb_4_3.setText(_translate("Frame", "3"))
        self.pb_4_5.setText(_translate("Frame", "5"))
        self.pb_4_23.setText(_translate("Frame", "23"))
        self.pb_4_9.setText(_translate("Frame", "9"))
        self.pb_2_17.setText(_translate("Frame", "17"))
        self.pb_1_14.setText(_translate("Frame", "14"))
        self.pb_1_4.setText(_translate("Frame", "4"))
        self.pb_3_3.setText(_translate("Frame", "3"))
        self.pb_2_8.setText(_translate("Frame", "8"))
        self.pb_2_21.setText(_translate("Frame", "21"))
        self.pb_4_26.setText(_translate("Frame", "26"))
        self.pb_1_18.setText(_translate("Frame", "18"))
        self.pb_4_16.setText(_translate("Frame", "16"))
        self.pb_1_24.setText(_translate("Frame", "24"))
        self.lbl_bar_code_3.setText(_translate("Frame", "000000000000000000"))
        self.pb_1_11.setText(_translate("Frame", "11"))
        self.pb_3_6.setText(_translate("Frame", "6"))
        self.pb_1_8.setText(_translate("Frame", "8"))
        self.pb_4_15.setText(_translate("Frame", "15"))
        self.pb_4_27.setText(_translate("Frame", "27"))
        self.lbl_test_no_2.setText(_translate("Frame", "?"))
        self.lbl_measurement_2.setText(_translate("Frame", "?"))
        self.lbl_ResultTest_2.setText(_translate("Frame", "?"))
        self.lbl_test_no_1.setText(_translate("Frame", "?"))
        self.lbl_measurement_1.setText(_translate("Frame", "?"))
        self.lbl_ResultTest_1.setText(_translate("Frame", "?"))
        self.lbl_lbl_test_no_1.setText(_translate("Frame", "Last test"))
        self.lbl_lbl_measurement_1.setText(_translate("Frame", "Value"))
        self.lbl_lbl_ResultTest.setText(_translate("Frame", "Status"))
        self.lbl_test_no_4.setText(_translate("Frame", "?"))
        self.lbl_measurement_4.setText(_translate("Frame", "?"))
        self.lbl_ResultTest_4.setText(_translate("Frame", "?"))
        self.lbl_test_no_3.setText(_translate("Frame", "?"))
        self.lbl_measurement_3.setText(_translate("Frame", "?"))
        self.lbl_ResultTest_3.setText(_translate("Frame", "?"))
        self.pb_2_6.setText(_translate("Frame", "6"))
        self.pb_4_14.setText(_translate("Frame", "14"))
        self.pb_3_2.setText(_translate("Frame", "2"))
        self.pb_2_3.setText(_translate("Frame", "3"))
        self.pb_4_29.setText(_translate("Frame", "29"))
        self.pb_1_20.setText(_translate("Frame", "20"))
        self.pb_3_1.setText(_translate("Frame", "1"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
